export interface WorkbenchAgent {
  id: string;
  name: string;
  role: string;
  status: string;
  task: string;
  /** Natural language summary of this agent's work, generated by Commander synthesis. */
  summaryText?: string;
}

export interface WorkbenchStep {
  id: string;
  title: string;
  status: string;
  successCriteria?: string;
  agentKind?: string;
  agentId?: string;
  startedAt?: string;
  completedAt?: string;
  durationMs?: number;
  errorSummary?: string;
}

export interface WorkbenchLogEntry {
  id: string;
  kind: string;
  title: string;
  detail: string;
  createdAt?: string;
  userMessage?: string;
  devDetail?: string;
  agentId?: string;
  stepId?: string;
}

export interface WorkbenchDocument {
  path: string;
  modifiedAt: string;
  sizeBytes: number;
  heading?: string;
  excerpt?: string;
  purpose: string;
}

export interface WorkbenchCommand {
  command: string;
  cwd: string;
  exitCode: number | null;
  stdout: string;
  stderr: string;
}

export interface WorkbenchPermissionRequest {
  id: string;
  level: string;
  writeRiskLevel?: "safe" | "risky" | "dangerous";
  title: string;
  reason: string;
  status: string;
  dryRun: {
    operation: string;
    affectedPaths: Array<{
      source: string;
      target: string;
      action: string;
      conflict?: string;
    }>;
    riskSummary: string;
    reversible: boolean;
  };
}

export type WorkbenchPermissionDecision = "approved" | "approved_always" | "denied";

export interface WorkbenchAskUserQuestion {
  id: string;
  question: string;
  choices?: Array<string | WorkbenchAskUserChoice>;
  status: string;
  answer?: string;
}

export interface WorkbenchAskUserChoice {
  label: string;
  value: string;
  isRecommended?: boolean;
}

export interface WorkbenchFileOrganizationExecution {
  attemptedCount: number;
  movedCount: number;
  skippedCount: number;
  failedCount: number;
  results: Array<{
    source: string;
    target: string;
    status: string;
    message: string;
  }>;
}

export interface WorkbenchProject {
  workspacePath: string;
  packageManager?: string;
  scripts: Array<{
    name: string;
    command: string;
  }>;
  recommendedStartCommand?: string;
  recommendedTestCommand?: string;
}

export interface WorkbenchSource {
  url: string;
  title?: string;
  excerpt: string;
  fetchedAt: string;
  provider?: string;
}

export interface WorkbenchResearchReport {
  title: string;
  summary: string;
  rows: Array<{
    claim: string;
    sourceUrl: string;
    evidence: string;
  }>;
  unknowns: string[];
}

export interface WorkbenchCodeReviewPreview {
  workspacePath: string;
  changedFiles: string[];
  diffStat: string;
  diff: string;
}

export interface WorkbenchCodeProposedEdit {
  approvalId?: string;
  proposalId: string;
  workspacePath: string;
  summary: string;
  changedFiles: string[];
  patch: string;
  patchHash: string;
}

export interface WorkbenchCodeApplyResult {
  applied: boolean;
  workspacePath: string;
  changedFiles: string[];
  message: string;
}

export interface WorkbenchTokenUsageSummary {
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  modelCalls: number;
  byAgentKind: Array<{
    agentKind: string;
    inputTokens: number;
    outputTokens: number;
    totalTokens: number;
    modelCalls: number;
  }>;
}

export type WorkbenchStreamingAgentKind =
  | "commander"
  | "file"
  | "shell"
  | "browser"
  | "computer"
  | "scheduler"
  | "research"
  | "code"
  | "verifier"
  | "workspace"
  | "vision";

export interface ProviderCatalogEntry {
  id: string;
  label: string;
  defaultBaseUrl: string;
  apiType: "openai-compatible" | "anthropic-messages";
  modelListMode: "openai" | "anthropic" | "unsupported";
}

export interface ProviderCapabilities {
  vision: boolean;
  code: boolean;
  longContext: boolean;
}

export interface WorkbenchModelSettings {
  provider: string;
  model: string;
  apiKey: string;
  apiKeyReference: string;
  baseUrl: string;
}

/** The three built-in model slots. */
export type WorkbenchModelSlot = "primary" | "secondary" | "multimodal";

/** A named model configuration for the UI. */
export interface WorkbenchModelProfile {
  id: string;
  slot: WorkbenchModelSlot | null;
  displayName: string;
  provider: string;
  model: string;
  apiKeyReference: string;
  baseUrl: string;
  apiKey: string;  // only used in UI, never persisted
  /** Whether an API key is already stored in the OS credential store for this profile. */
  hasStoredApiKey?: boolean;
  /** Explicit model context window in tokens when known. */
  contextTokens?: number;
  capabilities: {
    vision: boolean;
    code: boolean;
    longContext: boolean;
  };
}

/** Full model configuration for the UI. */
export interface WorkbenchModelConfiguration {
  profiles: WorkbenchModelProfile[];
  agentOverrides: Record<string, string>;
}

export interface WorkbenchAgentCatalogEntry {
  kind: string;
  displayName: string;
}

export interface WorkbenchAgentStyleState {
  kind: string;
  currentStyle: string;
  source: "global" | "workspace" | "none";
  filePath?: string;
}

export interface WorkbenchProgress {
  current: number;
  total: number;
  startedAt?: number;
}

export interface WorkbenchHistoryEntry {
  id: string;
  title: string;
  status: string;
  userGoal: string;
  updatedAt: string;
  originMode?: "chat" | "project";
  workspacePath?: string;
  scheduledTaskId?: string;
}

export type WorkbenchConversationMessageKind =
  | "user_text"
  | "assistant_text"
  | "ask_user_question"
  | "permission_request";

export interface WorkbenchChatMessage {
  id?: string;
  kind?: WorkbenchConversationMessageKind;
  role: "user" | "assistant";
  content: string;
  parentMessageId?: string;
  createdAt?: string;
  attachments?: string[];
  askUserQuestion?: WorkbenchAskUserQuestion;
  permissionRequest?: WorkbenchPermissionRequest;
}

export interface WorkbenchTask {
  id?: string;
  title: string;
  userGoal: string;
  status: string;
  updatedAt?: string;
  originMode?: "chat" | "project";
  workspacePath?: string;
  commanderMessage: string;
  plan: WorkbenchStep[];
  agents: WorkbenchAgent[];
  logs: WorkbenchLogEntry[];
  documents?: WorkbenchDocument[];
  commands?: WorkbenchCommand[];
  fileOrganizationExecution?: WorkbenchFileOrganizationExecution;
  permissionRequest?: WorkbenchPermissionRequest;
  askUserQuestion?: WorkbenchAskUserQuestion;
  project?: WorkbenchProject;
  codeReviewPreview?: WorkbenchCodeReviewPreview;
  codeProposedEdit?: WorkbenchCodeProposedEdit;
  codeApplyResult?: WorkbenchCodeApplyResult;
  researchReport?: WorkbenchResearchReport;
  sources?: WorkbenchSource[];
  tokenUsage?: WorkbenchTokenUsageSummary;
  verificationSummary?: string;
  conversationMessages?: WorkbenchChatMessage[];
  streamingText?: string;
  streamingAgentKind?: WorkbenchStreamingAgentKind;
  isStreaming?: boolean;
  executionTrace?: WorkbenchExecutionTrace;
  /** User-readable error message shown in recovery section when task fails. */
  userFacingError?: string;
}

export interface WorkbenchExecutionTrace {
  taskId: string;
  startedAt: string;
  completedAt?: string;
  totalWallTimeMs: number;
  steps: WorkbenchStepTrace[];
}

export interface WorkbenchStepTrace {
  stepId: string;
  agentKind: string;
  toolName?: string;
  wallTimeMs: number;
  status: "completed" | "failed" | "skipped";
}

/** View identifier. Built-in values: "chat" | "automated" | "skills" | "apps" | "documents" | "gallery" | "computer". Workspace definitions may register additional view IDs. */
export type ActiveView = string;
export type WorkbenchSkillPage = "mine" | "market";

export interface SidebarNavSubItem {
  label: string;
  path?: string;
  viewId?: ActiveView;
  category?: string;
  mode?: "chat" | "project";
  skillPage?: WorkbenchSkillPage;
  badge?: number;
  meta?: string;
  status?: "idle" | "running" | "completed" | "failed";
}

export interface SidebarNavItem {
  viewId: string;
  icon: string;
  label: string;
  group?: "primary" | "knowledge" | "custom";
  groupLabel?: string;
  order: number;
  badge?: number;
  meta?: string;
  status?: "idle" | "running" | "completed" | "failed";
  children?: SidebarNavSubItem[];
  /** If true, renders as a collapsible nav item with subitems. */
  collapsible?: boolean;
  subitems?: SidebarNavSubItem[];
}

export interface WorkbenchScheduledTask {
  id: string;
  name: string;
  goal: string;
  scheduleType: string;
  scheduleValue: string;
  enabled: boolean;
  nextRunAt: string;
  lastRunStatus: "running" | "success" | "failed" | "never";
  createdAt: string;
}

export interface WorkbenchSkillEntry {
  id: string;
  name: string;
  description: string;
  category: "tool" | "agent" | "mcp";
  permissionLevel?: string;
  agentOwners: string[];
  enabled: boolean;
}

export type WorkbenchSkillSearchKind = "skill" | "mcp";
export type WorkbenchSkillSearchSource = "github";

export interface WorkbenchSkillSearchResult {
  id: string;
  title: string;
  description: string;
  url: string;
  source: WorkbenchSkillSearchSource | string;
  kind: WorkbenchSkillSearchKind;
}

export interface WorkbenchDetailItem {
  title: string;
  description?: string;
  kind?: string;
  source?: string;
  url?: string;
  metadata?: Array<{ label: string; value: string }>;
}

export interface WorkbenchSystemResources {
  cpuPercent: number;
  memoryPercent: number;
  memoryUsedBytes?: number;
  memoryTotalBytes?: number;
}

export interface WorkbenchRecommendationItem {
  id: string;
  label: string;
  prompt: string;
  source?: "profile" | "workspace" | "history" | "default";
  confidence?: number;
  reason?: string;
  evidence?: WorkbenchRecommendationEvidence[];
}

export interface WorkbenchNewChatRecommendations {
  primary: WorkbenchRecommendationItem[];
  secondary: WorkbenchRecommendationItem[];
}

export interface WorkbenchRecommendationEvidence {
  title?: string;
  snippet: string;
  observedAt?: string;
  matchedKeywords?: string[];
}

export interface WorkbenchUserProfileMemoryFactSummary {
  id: string;
  text: string;
  tags: string[];
  source: "history" | "workspace";
  confidence: number;
  hitCount: number;
  evidence: WorkbenchRecommendationEvidence[];
}

export interface WorkbenchUserProfileMemorySummary {
  factCount: number;
  topTags: string[];
  updatedAt?: string;
  facts?: WorkbenchUserProfileMemoryFactSummary[];
}

export type WorkbenchWorkspaceToolAction =
  | "files"
  | "sideChat"
  | "browser"
  | "review"
  | "terminal"
  | "newDoc"
  | "codePatch"
  | "dataAnalysis";

export interface WorkbenchWorkspaceToolTab {
  id: string;
  tool: WorkbenchWorkspaceToolAction;
  title?: string;
}

export type WorkbenchPermissionMode = "read_only" | "confirmed_write" | "full_access";

export interface WorkbenchAgentSessionContext {
  sessionId: string;
  threadId: string;
  taskId?: string;
  workspaceRoot: string;
  permissionMode: WorkbenchPermissionMode;
  activeModel: string;
  activeBranch?: string;
  activeTool?: WorkbenchWorkspaceToolAction | null;
  selectedAgentId?: string;
}

export interface WorkbenchFileEntry {
  name: string;
  path: string;
  isDir: boolean;
  thumbnailUrl?: string;
  sizeBytes?: number;
  modifiedAt?: string;
  extension?: string;
  category?: string;
  tags?: string[];
  confidence?: number;
  /** Resource scan root ID this entry belongs to. Used for per-root refresh dedup. */
  sourceRootId?: string;
  /** Canonical resource scan root path this entry belongs to. */
  sourceRootPath?: string;
}

export interface ScanRootItem {
  id: string;
  path: string;
  label?: string;
  kinds: Array<"documents" | "images">;
  enabled: boolean;
  source: "default" | "custom";
}

export interface WorkbenchTrustedComputerApp {
  title: string;
  trustedAt: string;
}

export interface WorkbenchAppEntry {
  name: string;
  path: string;
  iconPath?: string;
  publisher?: string;
  installLocation?: string;
  category?: string;
  tags?: string[];
  confidence?: number;
}

export interface BrowserQuickResult {
  title?: string;
  url: string;
  content?: string;
  screenshotDataUrl?: string;
  loadState?: string;
  sidecarRunning?: boolean;
  canGoBack?: boolean;
  canGoForward?: boolean;
}

export type BrowserQuickAction = "status" | "navigate" | "refresh" | "back" | "forward";

export interface BrowserQuickRequest {
  action: BrowserQuickAction;
  url?: string;
}

export interface ReviewQuickResult {
  changedFiles: string[];
  diffStat: string;
  diff: string;
  workspacePath: string;
  branch?: string;
}

export interface TerminalQuickResult {
  stdout: string;
  stderr: string;
  exitCode: number | null;
  cwd: string;
  command: string;
}

export interface WorkbenchTerminalSession {
  terminalId: string;
  cwd: string;
  shell: string;
}

export interface WorkbenchFileSearchResult {
  path: string;
  line?: number;
  preview?: string;
}

export interface WorkbenchBrowserSnapshot {
  url?: string;
  title?: string;
  content?: string;
  screenshotDataUrl?: string;
  loadState?: string;
}

export interface WorkbenchTerminalService {
  create(
    session: WorkbenchAgentSessionContext,
    cols: number,
    rows: number,
    terminalId?: string,
  ): Promise<WorkbenchTerminalSession>;
  input(session: WorkbenchAgentSessionContext, terminalId: string, data: string): Promise<void>;
  resize(terminalId: string, cols: number, rows: number): Promise<void>;
  kill(terminalId: string): Promise<void>;
  subscribe(
    terminalId: string,
    handlers: {
      onOutput: (data: string) => void;
      onExit?: (exitCode: number | null) => void;
      onError?: (message: string) => void;
    },
  ): () => void;
}

export interface WorkbenchFileService {
  list(session: WorkbenchAgentSessionContext, path?: string): Promise<WorkbenchFileEntry[]>;
  search(session: WorkbenchAgentSessionContext, query: string): Promise<WorkbenchFileSearchResult[]>;
  watchStart?(session: WorkbenchAgentSessionContext): Promise<void>;
  watchStop?(session: WorkbenchAgentSessionContext): Promise<void>;
  subscribeChanged?(
    session: WorkbenchAgentSessionContext,
    handler: (paths: string[]) => void,
  ): () => void;
}

export interface JavisWorkbenchProps {
  task: WorkbenchTask;
  draftGoal: string;
  currentWorkspacePath?: string;
  historyEntries?: WorkbenchHistoryEntry[];
  locale?: WorkbenchLocale;
  agentCatalog?: WorkbenchAgentCatalogEntry[];
  modelSettings?: WorkbenchModelSettings;
  modelConfiguration?: WorkbenchModelConfiguration;
  newChatRecommendations?: WorkbenchNewChatRecommendations;
  userProfileMemorySummary?: WorkbenchUserProfileMemorySummary | null;
  recentWorkspacePaths?: string[];
  activeView?: ActiveView;
  activeHistoryEntryId?: string;
  scheduledTasks?: WorkbenchScheduledTask[];
  skillEntries?: WorkbenchSkillEntry[];
  skillTranslationStatus?: "idle" | "translating" | "error";
  skillTranslationError?: string | null;
  skillSearchResults?: WorkbenchSkillSearchResult[];
  skillSearchStatus?: "idle" | "searching" | "error";
  mcpConfigError?: string | null;
  /** Custom sidebar navigation items. Merged with built-in defaults. */
  sidebarNavItems?: SidebarNavItem[];
  installedApps?: WorkbenchAppEntry[];
  userDocuments?: WorkbenchFileEntry[];
  userImages?: WorkbenchFileEntry[];
  computerEntries?: WorkbenchFileEntry[];
  trustedComputerApps?: WorkbenchTrustedComputerApp[];
  computerPath?: string;
  mountRoots?: { name: string; path: string }[];
  isTaskActive?: boolean;
  appsLoading?: boolean;
  docsLoading?: boolean;
  imagesLoading?: boolean;
  computerLoading?: boolean;
  appsError?: string;
  docsError?: string;
  imagesError?: string;
  computerError?: string;
  // ── File classification ─────────────────────────────────────────
  scanning?: boolean;
  scanProgress?: WorkbenchProgress;
  appsProgress?: WorkbenchProgress;
  docsProgress?: WorkbenchProgress;
  imagesProgress?: WorkbenchProgress;
  classifying?: boolean;
  classifyProgress?: WorkbenchProgress & { completed?: number };
  appsClassifying?: boolean;
  appsClassifyProgress?: WorkbenchProgress & { completed?: number };
  categoryStats?: { category: string; count: number }[];
  appCategoryStats?: { category: string; count: number }[];
  /** Resource scan roots (default + custom) for docs/images views. */
  resourceScanRoots?: ScanRootItem[];
  onRefreshScan?: () => void;
  onClassifyDocuments?: () => void;
  onClassifyApps?: () => void;
  onCancelClassify?: () => void;
  onCancelClassifyApps?: () => void;
  onToggleScanRoot?: (id: string, enabled: boolean) => void;
  onRemoveScanRoot?: (id: string) => void;
  onAddScanRoot?: (path: string, kinds: Array<"documents" | "images">, label?: string) => void;
  onRefreshScanRoot?: (id: string) => void;
  onDraftGoalChange: (nextGoal: string) => void;
  onDeleteHistoryEntry?: (id: string) => void;
  onDeleteRecentWorkspacePath?: (path: string) => void;
  onBrowseWorkspacePath?: () => void;
  onModelSettingsChange?: (settings: WorkbenchModelSettings) => void;
  onTestModelConnection?: (settings: WorkbenchModelSettings) => Promise<string | void>;
  onModelConfigurationChange?: (config: WorkbenchModelConfiguration) => void;
  onRebuildUserProfileMemory?: () => void;
  onClearUserProfileMemory?: () => void;
  onReadAgentStyle?: (kind: string) => Promise<WorkbenchAgentStyleState>;
  onSaveAgentStyle?: (kind: string, content: string) => Promise<WorkbenchAgentStyleState | void>;
  onResetAgentStyle?: (kind: string) => Promise<WorkbenchAgentStyleState | void>;
  onSaveProviderApiKey?: (keyReference: string, apiKey: string) => Promise<void>;
  onFetchProviderModels?: (params: {
    provider: string;
    baseUrl: string;
    apiKey: string;
    apiType: string;
    keyReference: string;
    modelListMode: "openai" | "anthropic" | "unsupported";
  }) => Promise<string[]>;
  /** External provider catalog from @javis/core. When provided, replaces the built-in catalog. */
  providerCatalog?: readonly ProviderCatalogEntry[];
  /** Resolve default capabilities for a provider from its registered adapter. */
  getProviderCapabilities?: (provider: string) => ProviderCapabilities;
  terminalService?: WorkbenchTerminalService;
  fileService?: WorkbenchFileService;
  onSelectHistoryEntry?: (id: string) => void;
  onUseWorkspacePath?: (path: string) => void;
  onWorkspacePathChange?: (path: string) => void;
  onPermissionDecision?: (decision: WorkbenchPermissionDecision) => void;
  onAskUserAnswer?: (answer: string) => void;
  onRetryTask?: () => void;
  onStopTask?: () => void;
  onConversationMessagesChange?: (taskId: string | undefined, messages: WorkbenchChatMessage[]) => void;
  /** When user clicks an agent summary card in the chat, selected agent ID + open right sidebar. */
  onSelectAgent?: (agentId: string) => void;
  onSubmitGoal: (goal?: string, workspacePath?: string, scheduledTaskId?: string, attachments?: File[], imageDataUrls?: string[]) => void;
  onTranslateSkillsToChinese?: () => void;
  onSearchSkillMarket?: (
    query: string,
    source: WorkbenchSkillSearchSource,
    kind: WorkbenchSkillSearchKind,
  ) => void;
  onOpenDetail?: (detail: WorkbenchDetailItem) => void;
  onOpenWorkspaceTool?: (action: WorkbenchWorkspaceToolAction) => void;
  onChangeActiveView?: (view: ActiveView) => void;
  onSelectComposeMode?: (mode: "chat" | "project") => void;
  activeComposeMode?: "chat" | "project";
  onToggleScheduledTask?: (id: string) => void;
  onDeleteScheduledTask?: (id: string) => void;
  onRefreshApps?: () => void;
  onUpdateAppCategory?: (path: string, category: string) => void;
  onRefreshDocuments?: () => void;
  onRefreshImages?: () => void;
  onNavigateDirectory?: (path: string) => void;
  onListDirectory?: (path: string) => Promise<WorkbenchFileEntry[]>;
  onOpenFile?: (path: string) => void;
  onRemoveTrustedComputerApp?: (title: string) => void;
  onSidebarWidthChange?: (width: number) => void;
  onActiveViewChange?: (view: ActiveView) => void;
  onSidebarOpenChange?: (open: boolean) => void;
  onActivityOpenChange?: (open: boolean) => void;
  onInspectorOpenChange?: (open: boolean) => void;
  onActivityHeightChange?: (height: number) => void;
  /** Open workspace tool tabs in the inspector. Last tab is active. */
  openTabs?: WorkbenchWorkspaceToolAction[];
  workspaceToolTabs?: WorkbenchWorkspaceToolTab[];
  onActiveToolChange?: (tool: WorkbenchWorkspaceToolAction | null) => void;
  /** Browser tool — navigate to URL, returns page metadata. */
  onQuickActionBrowser?: (session: WorkbenchAgentSessionContext, request: string | BrowserQuickRequest) => Promise<BrowserQuickResult>;
  /** Review tool — run git diff and return review data. */
  onQuickActionReview?: (session: WorkbenchAgentSessionContext) => Promise<ReviewQuickResult>;
  /** Terminal tool — run a shell command and return output. */
  onQuickActionTerminal?: (session: WorkbenchAgentSessionContext, command: string) => Promise<TerminalQuickResult>;
  /** SideChat tool — send a message and get AI response. */
  onQuickActionSideChat?: (session: WorkbenchAgentSessionContext, message: string) => Promise<string>;
  initialSidebarWidth?: number;
  initialActivityHeight?: number;
  initialIsSidebarOpen?: boolean;
  initialIsActivityOpen?: boolean;
  initialIsInspectorOpen?: boolean;
  systemResources?: WorkbenchSystemResources;
}

export interface WorkbenchLocale {
  categoryLabels?: Record<string, string>;
  labels: {
    activeTask: string;
    activityLog: string;
    addPhotosAndFiles: string;
    addedAttachments: string;
    accountSettings: string;
    aiModeSettings: string;
    apps: string;
    askUserQuestion: string;
    automatedTasks: string;
    collapseActivityLog: string;
    collapseSidebar: string;
    agentContextInspector: string;
    agentGraph: string;
    agentStates: string;
    collapseInspector: string;
    approve: string;
    alwaysAllow: string;
    allLevels: string;
    commandResults: string;
    commander: string;
    codeReview: string;
    changedFiles: string;
    closeSettings: string;
    clearLogs: string;
    completed: string;
    currentTask: string;
    deny: string;
    deleteHistoryEntry: string;
    documents: string;
    emptyOutput: string;
    executionTimeline: string;
    expandActivityLog: string;
    expandSidebar: string;
    expandInspector: string;
    failed: string;
    layoutPresetChat: string;
    layoutPresetExpanded: string;
    layoutPresetFocus: string;
    layoutPresets: string;
    fileOrganizationResult: string;
    filterLogs: string;
    failedRecoveryTitle: string;
    failedRecoveryMessage: string;
    gallery: string;
    generalSettings: string;
    history: string;
    historyEmpty: string;
    historyEmptyGroup: string;
    historyNoMatches: string;
    expandHistoryGroup: string;
    hideProcessDetails: string;
    localKnowledgeBase: string;
    logLevelFilter: string;
    mainThread: string;
    manualSourceFallbackTitle: string;
    manualSourceFallbackMessage: string;
    markdownDocuments: string;
    models: string;
    modelProvider?: string;
    modelName?: string;
    modelApiKey?: string;
    modelBaseUrl?: string;
    modelSettingsDescription?: string;
    modelBackendUnavailable?: string;
    modified: string;
    moreInputOptions: string;
    newChat: string;
    newChatTitle: string;
    chatNewChatTitle: string;
    chat: string;
    office: string;
    packageScript: string;
    plan: string;
    planMode: string;
    plugins: string;
    projectInspection: string;
    project: string;
    processDetails: string;
    projects: string;
    profileName: string;
    researchReport: string;
    researchSources: string;
    retryTask: string;
    running: string;
    send: string;
    stopTask: string;
    submitAnswer: string;
    searchPlaceholder: string;
    settings: string;
    settingsPlaceholder: string;
    showProcessDetails: string;
    skillMarket: string;
    source: string;
    status: string;
    taskInput: string;
    taskInputPlaceholder: string;
    chatTaskInputPlaceholder: string;
    testCheck: string;
    thisComputer: string;
    tokenUsage: string;
    tokenInput: string;
    tokenOutput: string;
    tokenCalls: string;
    trustedComputerApps: string;
    removeTrustedApp: string;
    contextWindow: string;
    contextUsed: string;
    contextRemaining: string;
    contextBreakdown: string;
    noModelCalls: string;
    unknown: string;
    unknownManager: string;
    unverified: string;
    user: string;
    verifier: string;
    workspaceNavigation: string;
    workspaceControls: string;
    waiting: string;
    sidebarResize: string;
    browseWorkspace: string;
    currentWorkspace: string;
    recentWorkspaces: string;
    removeAttachment: string;
    removeWorkspace: string;
    useWorkspace: string;
    workspaceBrowseError: string;
    workspacePathPlaceholder: string;
    automatedTasksTitle: string;
    scheduledTaskEnabled: string;
    scheduledTaskDisabled: string;
    scheduledTaskNextRun: string;
    scheduledTaskLastRun: string;
    skillMarketTitle: string;
    skillCategoryTool: string;
    skillCategoryAgent: string;
    skillCategoryMcp: string;
    noMcpConfig: string;
    mcpLoadError?: string;
    skillUiFeatureLabel: string;
    privacySecuritySettings: string;
    aboutFeedbackSettings: string;
    appsTitle: string;
    documentsTitle: string;
    galleryTitle: string;
    computerTitle: string;
    fileExplorerBreadcrumb: string;
    fileExplorerEmpty: string;
    scanInProgress: string;
    scanComplete: string;
    noAppsFound: string;
    noDocumentsFound: string;
    noImagesFound: string;
    noScheduledTasks: string;
    scanFailed: string;
    retry: string;
    unknownView: string;
    kbDocRecognition: string;
    kbCourseware: string;
    kbBooks: string;
    kbPapers: string;
    kbImageRecognition: string;
    kbPeopleImpressions: string;
    kbFootprintLocations: string;
    kbTimelineGallery: string;
    kbSystemDrive: string;
    kbDriveE: string;
    kbDriveF: string;
    kbDriveG: string;
    classifyButton: string;
    cancelClassify: string;
    classifyProgress: string;
    classifyFailed: string;
    allCategories: string;
    categoryBadge: string;
    confidenceLabel: string;
  };
  phrases?: Record<string, string>;
}
