export interface WorkbenchAgent {
  id: string;
  name: string;
  role: string;
  status: string;
  task: string;
  /** Natural language summary of this agent's work, generated by Commander synthesis. */
  summaryText?: string;
  capabilityScore?: WorkbenchAgentCapabilityScore;
}

export interface WorkbenchAgentCapabilityScore {
  score: number;
  status: "ready" | "usable" | "partial" | "limited";
  implemented: boolean;
  permissionReady: boolean;
  qaPassed: boolean;
  liveVerified: boolean;
  recentFailureRate: number;
  highestPermissionLevel: string;
  capabilityTags: string[];
  evidenceRefs: string[];
  gaps: string[];
}

export interface WorkbenchStep {
  id: string;
  title: string;
  status: string;
  successCriteria?: string;
  agentKind?: string;
  agentId?: string;
  inputContextKeys?: string[];
  outputContextKey?: string;
  startedAt?: string;
  completedAt?: string;
  durationMs?: number;
  errorSummary?: string;
}

export interface WorkbenchLogEntry {
  id: string;
  kind: string;
  title: string;
  detail: string;
  createdAt?: string;
  userMessage?: string;
  devDetail?: string;
  agentId?: string;
  stepId?: string;
}

export interface WorkbenchDocument {
  path: string;
  modifiedAt: string;
  sizeBytes: number;
  heading?: string;
  excerpt?: string;
  purpose: string;
}

export interface WorkbenchCommand {
  command: string;
  cwd: string;
  exitCode: number | null;
  stdout: string;
  stderr: string;
}

export interface WorkbenchPermissionRequest {
  id: string;
  level: string;
  writeRiskLevel?: "safe" | "risky" | "dangerous";
  title: string;
  reason: string;
  status: string;
  allowAlways?: boolean;
  screenshotDataUrl?: string;
  dryRun: {
    operation: string;
    affectedPaths: Array<{
      source: string;
      target: string;
      action: string;
      conflict?: string;
    }>;
    riskSummary: string;
    reversible: boolean;
  };
}

export type WorkbenchPermissionDecision = "approved" | "approved_always" | "denied";

export interface WorkbenchAskUserQuestion {
  id: string;
  question: string;
  choices?: Array<string | WorkbenchAskUserChoice>;
  status: string;
  answer?: string;
  resolvedAt?: string;
}

export interface WorkbenchAskUserChoice {
  label: string;
  value: string;
  isRecommended?: boolean;
}

export interface WorkbenchFileOrganizationExecution {
  attemptedCount: number;
  movedCount: number;
  skippedCount: number;
  failedCount: number;
  results: Array<{
    source: string;
    target: string;
    status: string;
    message: string;
  }>;
}

export interface WorkbenchProject {
  workspacePath: string;
  packageManager?: string;
  scripts: Array<{
    name: string;
    command: string;
  }>;
  recommendedStartCommand?: string;
  recommendedTestCommand?: string;
}

export interface WorkbenchSource {
  url: string;
  title?: string;
  excerpt: string;
  fetchedAt: string;
  provider?: string;
}

export interface WorkbenchResearchReport {
  title: string;
  summary: string;
  rows: Array<{
    claim: string;
    status?: "verified" | "unknown";
    sourceUrl: string;
    excerpt?: string;
    evidence: string;
    verificationStatus?: "verified" | "unknown";
    sourceProvider?: string;
  }>;
  unknowns: string[];
}

export interface WorkbenchCodeReviewPreview {
  workspacePath: string;
  changedFiles: string[];
  diffStat: string;
  diff: string;
}

export interface WorkbenchCodeProposedEdit {
  approvalId?: string;
  proposalId: string;
  workspacePath: string;
  summary: string;
  changedFiles: string[];
  patch: string;
  patchHash: string;
}

export interface WorkbenchCodeApplyResult {
  applied: boolean;
  workspacePath: string;
  changedFiles: string[];
  message: string;
}

export interface WorkbenchTokenUsageSummary {
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  modelCalls: number;
  byAgentKind: Array<{
    agentKind: string;
    inputTokens: number;
    outputTokens: number;
    totalTokens: number;
    modelCalls: number;
  }>;
}

export type WorkbenchStreamingAgentKind =
  | "commander"
  | "file"
  | "shell"
  | "browser"
  | "computer"
  | "scheduler"
  | "research"
  | "code"
  | "language-reviewer"
  | "security-reviewer"
  | "build-fix"
  | "test-runner"
  | "doc-updater"
  | "explorer"
  | "perf-analyzer"
  | "refactor"
  | "verifier"
  | "workspace"
  | "vision";

export interface ProviderCatalogEntry {
  id: string;
  label: string;
  defaultBaseUrl: string;
  apiType: "openai-compatible" | "anthropic-messages";
  modelListMode: "openai" | "anthropic" | "unsupported";
}

export interface ProviderCapabilities {
  vision: boolean;
  code: boolean;
  longContext: boolean;
}

export interface WorkbenchModelSettings {
  provider: string;
  model: string;
  apiKey: string;
  apiKeyReference: string;
  baseUrl: string;
}

export type WorkbenchComputerUseLocalVisionMode = "off" | "passive" | "prompt_hint";
export type WorkbenchComputerUseLocalVisionRuntime = "auto" | "onnxruntime" | "openvino" | "tensorrt";

export interface WorkbenchComputerUseLocalVisionSettings {
  mode: WorkbenchComputerUseLocalVisionMode;
  modelPath: string;
  runtime: WorkbenchComputerUseLocalVisionRuntime;
  runtimeAdapterPath: string;
  imgsz: number;
  timeoutMs: number;
  maxDetections: number;
  minConfidence: number;
  iouThreshold: number;
  promptTopK: number;
  disableAfterConsecutiveTimeouts: number;
  disableAfterConsecutiveErrors: number;
  disableAfterConsecutiveActionFailures: number;
  reuseWorker: boolean;
}

export interface WorkbenchComputerUseSettings {
  enabled: boolean;
  maxStepsPerTask: number;
  mouseSpeed: "instant" | "linear";
  mouseDurationMs: number;
  typeDelayMs: number;
  deniedWindowPatterns: string[];
}

export type WorkbenchDefaultStartupMode = "chat" | "project" | "auto";
export type WorkbenchContextStrategy = "auto" | "short" | "long";
export type WorkbenchAgentMaxRoundsPreset = "4" | "8" | "12" | "custom";
export type WorkbenchTaskTimeoutPreset = "standard" | "long" | "custom";
export type WorkbenchAgentMemoryScopeMode = "off" | "workspace" | "global_workspace";
export type WorkbenchAgentMemoryEmbeddingMode = "local" | "openai_compatible";
export type WorkbenchTaskQueuePolicy = "queue" | "current_only" | "interrupt";
export type WorkbenchFailureRecoveryPolicy = "replan" | "stop";
export type WorkbenchUserWaitTimeoutPreset = "standard" | "long" | "custom";
export type WorkbenchAppearanceTheme = "light" | "dark" | "glass" | "high_contrast";

export interface WorkbenchRuntimePreferences {
  appearanceTheme: WorkbenchAppearanceTheme;
  defaultStartupMode: WorkbenchDefaultStartupMode;
  contextStrategy: WorkbenchContextStrategy;
  agentMaxRoundsPreset: WorkbenchAgentMaxRoundsPreset;
  agentMaxRoundsCustom: number;
  taskTimeoutPreset: WorkbenchTaskTimeoutPreset;
  taskTimeoutCustomMs: number;
  agentMemoryScope: WorkbenchAgentMemoryScopeMode;
  agentMemoryEmbeddingMode: WorkbenchAgentMemoryEmbeddingMode;
  agentMemoryEmbeddingProvider: string;
  agentMemoryEmbeddingModel: string;
  agentMemoryEmbeddingBaseUrl: string;
  agentMemoryEmbeddingApiKeyReference: string;
  agentMemoryEmbeddingDimensions: number;
  taskQueuePolicy: WorkbenchTaskQueuePolicy;
  failureRecoveryPolicy: WorkbenchFailureRecoveryPolicy;
  userWaitTimeoutPreset: WorkbenchUserWaitTimeoutPreset;
  userWaitTimeoutCustomMs: number;
}

export type WorkbenchGoalStatus = "active" | "paused" | "complete" | "blocked" | "cleared";

export interface WorkbenchGoalState {
  id: string;
  objective: string;
  acceptanceCriteria: string[];
  status: WorkbenchGoalStatus;
  workspacePath?: string;
  taskIds: string[];
  completedChecks: string[];
  blockedReason?: string;
  blockedStreak: number;
  runCount: number;
  maxRunCount: number;
  createdAt: string;
  updatedAt: string;
}

export type WorkbenchGoalDecisionStatus = "complete" | "continue" | "blocked";
export type WorkbenchGoalConfidence = "low" | "medium" | "high";

export type WorkbenchGoalEventType =
  | "created"
  | "task_bound"
  | "task_terminal"
  | "evaluated"
  | "continued"
  | "paused"
  | "resumed"
  | "completed"
  | "blocked"
  | "cleared"
  | "strategy_applied"
  | "handoff_requested"
  | "self_refine_started";

export interface WorkbenchGoalEvaluation {
  id: string;
  goalId: string;
  taskId: string;
  decision: WorkbenchGoalDecisionStatus;
  confidence: WorkbenchGoalConfidence;
  satisfiedCriteria: string[];
  unsatisfiedCriteria: string[];
  evidence: string[];
  completedChecks: string[];
  nextPrompt?: string;
  blockedReason?: string;
  reason: string;
  createdAt: string;
}

export interface WorkbenchGoalEvent {
  id: string;
  goalId: string;
  runId?: string;
  taskId?: string;
  type: WorkbenchGoalEventType;
  message?: string;
  payloadJson?: string;
  createdAt: string;
}

/** The three built-in model slots. */
export type WorkbenchModelSlot = "primary" | "secondary" | "multimodal";

/** A named model configuration for the UI. */
export interface WorkbenchModelProfile {
  id: string;
  slot: WorkbenchModelSlot | null;
  displayName: string;
  provider: string;
  model: string;
  apiKeyReference: string;
  baseUrl: string;
  apiKey: string;  // only used in UI, never persisted
  /** Whether an API key is already stored in the OS credential store for this profile. */
  hasStoredApiKey?: boolean;
  /** Explicit model context window in tokens when known. */
  contextTokens?: number;
  capabilities: {
    vision: boolean;
    code: boolean;
    longContext: boolean;
  };
}

/** Full model configuration for the UI. */
export interface WorkbenchModelConfiguration {
  profiles: WorkbenchModelProfile[];
  agentOverrides: Record<string, string>;
}

export interface WorkbenchAgentCatalogEntry {
  kind: string;
  displayName: string;
}

export interface WorkbenchAgentStyleState {
  kind: string;
  currentStyle: string;
  source: "global" | "workspace" | "none";
  filePath?: string;
}

export interface WorkbenchProgress {
  current: number;
  total: number;
  startedAt?: number;
}

export interface WorkbenchHistoryEntry {
  id: string;
  title: string;
  status: string;
  userGoal: string;
  updatedAt: string;
  originMode?: "chat" | "project";
  workspacePath?: string;
  scheduledTaskId?: string;
}

export type WorkbenchSubmitGoalIntent =
  | "new_chat"
  | "continue_history"
  | "queued_continuation"
  | "scheduled"
  | "goal";

export interface WorkbenchSubmitGoalOptions {
  intent?: WorkbenchSubmitGoalIntent;
}

export type WorkbenchConversationMessageKind =
  | "user_text"
  | "assistant_text"
  | "ask_user_question"
  | "permission_request";

export interface WorkbenchChatMessage {
  id?: string;
  kind?: WorkbenchConversationMessageKind;
  role: "user" | "assistant";
  content: string;
  parentMessageId?: string;
  createdAt?: string;
  attachments?: string[];
  askUserQuestion?: WorkbenchAskUserQuestion;
  permissionRequest?: WorkbenchPermissionRequest;
}

export interface WorkbenchTask {
  id?: string;
  title: string;
  userGoal: string;
  status: string;
  updatedAt?: string;
  originMode?: "chat" | "project";
  workspacePath?: string;
  commanderMessage: string;
  plan: WorkbenchStep[];
  agents: WorkbenchAgent[];
  logs: WorkbenchLogEntry[];
  documents?: WorkbenchDocument[];
  commands?: WorkbenchCommand[];
  fileOrganizationExecution?: WorkbenchFileOrganizationExecution;
  permissionRequest?: WorkbenchPermissionRequest;
  askUserQuestion?: WorkbenchAskUserQuestion;
  project?: WorkbenchProject;
  codeReviewPreview?: WorkbenchCodeReviewPreview;
  codeProposedEdit?: WorkbenchCodeProposedEdit;
  codeApplyResult?: WorkbenchCodeApplyResult;
  repoSearchReport?: WorkbenchRepositorySearchResult;
  repoTraceReport?: WorkbenchRepositoryTraceResult;
  researchReport?: WorkbenchResearchReport;
  sources?: WorkbenchSource[];
  tokenUsage?: WorkbenchTokenUsageSummary;
  verificationSummary?: string;
  conversationMessages?: WorkbenchChatMessage[];
  streamingText?: string;
  streamingAgentKind?: WorkbenchStreamingAgentKind;
  isStreaming?: boolean;
  executionTrace?: WorkbenchExecutionTrace;
  handoffReport?: WorkbenchHandoffReport;
  recoveryReport?: WorkbenchRecoveryReport;
  /** User-readable error message shown in recovery section when task fails. */
  userFacingError?: string;
}

export interface WorkbenchHandoffReport {
  generatedAt: string;
  steps: WorkbenchHandoffReportStep[];
  handoffs: WorkbenchHandoffRecord[];
  missingInputContextKeys: string[];
  invalidInputContextKeys: string[];
  unconsumedOutputContextKeys: string[];
  status: "complete" | "needs_attention";
}

export interface WorkbenchHandoffReportStep {
  stepId: string;
  title?: string;
  assignedAgentKind: string;
  dependsOn: string[];
  inputContextKeys: string[];
  outputContextKey?: string;
  missingInputContextKeys: string[];
  invalidInputContextKeys: string[];
  successCriteria?: string;
}

export interface WorkbenchHandoffRecord {
  contextKey: string;
  producedByStepId?: string;
  consumedByStepIds: string[];
  status: "available" | "missing" | "unconsumed" | "input_missing" | "invalid_schema";
  valueSummary: WorkbenchHandoffValueSummary;
  schemaError?: string;
}

export interface WorkbenchHandoffValueSummary {
  type: "array" | "object" | "string" | "number" | "boolean" | "null" | "undefined" | "unknown";
  present: boolean;
  itemCount?: number;
  keyCount?: number;
  preview?: string;
}

export interface WorkbenchRecoveryReport {
  generatedAt: string;
  status: "not_needed" | "recovered" | "needs_attention";
  failureCount: number;
  recoveredCount: number;
  unrecoveredCount: number;
  abandonedStepIds: string[];
  replannedStepIds: string[];
  attempts: WorkbenchRecoveryAttemptRecord[];
}

export interface WorkbenchRecoveryAttemptRecord {
  failedStepId: string;
  failedStepTitle?: string;
  agentKind?: string;
  errorSummary: string;
  failureKind: "timeout" | "permission_denied" | "unavailable" | "network" | "validation" | "unknown";
  completedBefore: string[];
  replanAttempted: boolean;
  replanStatus: "not_attempted" | "planned" | "failed";
  abandonedFailedStep: boolean;
  recoveryStepIds: string[];
  suggestedAlternatives: string[];
  detail?: string;
}

export interface WorkbenchRepositorySearchResult {
  actualFound: WorkbenchRepositorySearchMatch[];
  inferred: string[];
  needsConfirmation: string[];
  keyFiles: string[];
  relatedTestFiles: string[];
  testFileCandidates: string[];
  clusters: WorkbenchRepositorySearchCluster[];
  semanticDiagnostics?: Array<{
    provider: string;
    status: "completed" | "failed" | "skipped";
    candidateCount: number;
    rerankedCount: number;
    durationMs?: number;
    error?: string;
  }>;
  attempts: WorkbenchRepositorySearchAttempt[];
}

export interface WorkbenchRepositoryTraceResult {
  target: string;
  direction: "forward" | "backward" | "bidirectional";
  actualFound: WorkbenchRepositorySearchMatch[];
  nodes: Array<{
    id: string;
    label: string;
    kind: "target" | "entrypoint" | "candidate";
    path?: string;
    symbol?: string;
    score: number;
  }>;
  edges: Array<{
    from: string;
    to: string;
    relation: "references" | "may_call" | "imports" | "exports" | "entrypoint_to_candidate";
    evidencePath: string;
    line?: number;
    excerpt: string;
    confidence: number;
    moduleSpecifier?: string;
    moduleKind?: "relative" | "workspace" | "external";
  }>;
  moduleLinks: Array<{
    specifier: string;
    kind: "relative" | "workspace" | "external";
    evidencePaths: string[];
    importCount: number;
    exportCount: number;
    dynamicImportCount: number;
    confidence: number;
    resolutionStatus?: "resolved" | "unresolved" | "failed";
    resolvedPaths?: string[];
    resolverProvider?: string;
    resolutionError?: string;
    packageHints?: Array<{
      manifestPath: string;
      name?: string;
      main?: string;
      module?: string;
      types?: string;
      exports?: string[];
    }>;
  }>;
  inferred: string[];
  needsConfirmation: string[];
  keyFiles: string[];
  attempts: Array<{
    id: string;
    query: string;
    reason: string;
    resultCount?: number;
    status?: "completed" | "failed";
    durationMs?: number;
    error?: string;
    errorKind?: WorkbenchRepositorySearchAttemptErrorKind;
    provider?: string;
    retryCount?: number;
  }>;
}

export interface WorkbenchRepositorySearchMatch {
  path: string;
  line?: number;
  column?: number;
  excerpt: string;
  matchedTerms: string[];
  score?: number;
}

export interface WorkbenchRepositorySearchCluster {
  id: string;
  label: string;
  paths: string[];
  resultCount: number;
  score: number;
  topTerms: string[];
}

export interface WorkbenchRepositorySearchAttempt {
  id: string;
  query: string;
  reason: string;
  resultCount?: number;
  status?: "completed" | "failed";
  durationMs?: number;
  error?: string;
  errorKind?: WorkbenchRepositorySearchAttemptErrorKind;
  provider?: string;
  retryCount?: number;
}

export type WorkbenchRepositorySearchAttemptErrorKind = "timeout" | "unavailable" | "permission" | "cancelled" | "unknown";

export interface WorkbenchExecutionTrace {
  taskId: string;
  startedAt: string;
  completedAt?: string;
  totalWallTimeMs: number;
  steps: WorkbenchStepTrace[];
}

export interface WorkbenchStepTrace {
  stepId: string;
  agentKind: string;
  toolName?: string;
  wallTimeMs: number;
  status: "completed" | "failed" | "skipped";
  localVision?: {
    mode: "off" | "passive" | "prompt_hint" | "timeout" | "error" | "disabled" | "not_available";
    detectionCount?: number;
    promptCandidateCount?: number;
    latencyMs?: number;
    fullScreenshotVlmCalled?: boolean;
    cropVlmCalled?: boolean;
    fullScreenshotVlmSkipped?: boolean;
    consecutiveTimeouts?: number;
    consecutiveErrors?: number;
    consecutiveActionFailures?: number;
    consecutiveSlowDetections?: number;
    effectiveImgSize?: number;
    disabledReason?: "timeout" | "error" | "action_failure";
    selectedCandidateSource?: string[];
    actionType?: string;
    actionRisk?: "low" | "medium" | "high";
    actionSucceeded?: boolean;
    fallbackReason?: string;
  };
}

/** View identifier. Built-in values: "chat" | "automated" | "skills" | "apps" | "documents" | "gallery" | "computer". Workspace definitions may register additional view IDs. */
export type ActiveView = string;
export type WorkbenchSkillPage = "mine" | "market";

export interface SidebarNavSubItem {
  label: string;
  path?: string;
  viewId?: ActiveView;
  category?: string;
  mode?: "chat" | "project";
  skillPage?: WorkbenchSkillPage;
  badge?: number;
  meta?: string;
  status?: "idle" | "running" | "completed" | "failed";
}

export interface SidebarNavItem {
  viewId: string;
  icon: string;
  label: string;
  group?: "primary" | "knowledge" | "custom";
  groupLabel?: string;
  order: number;
  badge?: number;
  meta?: string;
  status?: "idle" | "running" | "completed" | "failed";
  children?: SidebarNavSubItem[];
  /** If true, renders as a collapsible nav item with subitems. */
  collapsible?: boolean;
  subitems?: SidebarNavSubItem[];
}

export interface WorkbenchScheduledTask {
  id: string;
  name: string;
  goal: string;
  scheduleType: string;
  scheduleValue: string;
  enabled: boolean;
  nextRunAt: string;
  lastRunStatus: "running" | "success" | "failed" | "never";
  createdAt: string;
}

export interface WorkbenchScheduledTaskDraft {
  name: string;
  goal: string;
  workspacePath: string;
  scheduleType: "interval" | "daily" | "weekly" | "once";
  scheduleValue: string;
}

export interface WorkbenchSkillEntry {
  id: string;
  name: string;
  description: string;
  category: "tool" | "agent" | "mcp" | "skill";
  permissionLevel?: string;
  agentOwners: string[];
  enabled: boolean;
  source?: "builtin" | "user" | "mcp";
  path?: string;
  toggleable?: boolean;
  removable?: boolean;
  installError?: string;
}

export type WorkbenchSkillSearchKind = "skill" | "mcp";
export type WorkbenchSkillSearchSource = "github";

export interface WorkbenchSkillSearchResult {
  id: string;
  title: string;
  description: string;
  url: string;
  source: WorkbenchSkillSearchSource | string;
  kind: WorkbenchSkillSearchKind;
  installed?: boolean;
  installing?: boolean;
  installError?: string;
}

export interface WorkbenchSkillSuggestion {
  title: string;
  description: string;
  url?: string;
  source?: string;
}

export interface WorkbenchDetailItem {
  title: string;
  description?: string;
  kind?: string;
  source?: string;
  url?: string;
  metadata?: Array<{ label: string; value: string }>;
}

export interface WorkbenchSystemResources {
  cpuPercent: number;
  memoryPercent: number;
  memoryUsedBytes?: number;
  memoryTotalBytes?: number;
}

export interface WorkbenchRecommendationItem {
  id: string;
  label: string;
  prompt: string;
  source?: "profile" | "workspace" | "history" | "default";
  confidence?: number;
  reason?: string;
  evidence?: WorkbenchRecommendationEvidence[];
}

export interface WorkbenchNewChatRecommendations {
  primary: WorkbenchRecommendationItem[];
  secondary: WorkbenchRecommendationItem[];
}

export interface WorkbenchRecommendationEvidence {
  title?: string;
  snippet: string;
  observedAt?: string;
  matchedKeywords?: string[];
}

export interface WorkbenchUserProfileMemoryFactSummary {
  id: string;
  text: string;
  tags: string[];
  source: "history" | "workspace";
  confidence: number;
  hitCount: number;
  evidence: WorkbenchRecommendationEvidence[];
}

export interface WorkbenchUserProfileMemorySummary {
  factCount: number;
  topTags: string[];
  updatedAt?: string;
  facts?: WorkbenchUserProfileMemoryFactSummary[];
}

export interface WorkbenchAgentMemoryFactPreview {
  id: string;
  fact: string;
  kind: string;
  tags: string[];
  scopeType: "global" | "workspace" | "session";
  scopeId?: string;
  confidence: number;
  importance: number;
  updatedAt: number;
}

export interface WorkbenchAgentMemorySummary {
  enabled: boolean;
  totalFactCount: number;
  workspaceFactCount: number;
  sessionSummaryCount: number;
  injectionLogCount: number;
  lastUpdatedAt?: number;
  recentFacts: WorkbenchAgentMemoryFactPreview[];
}

export type WorkbenchWorkspaceToolAction =
  | "files"
  | "sideChat"
  | "browser"
  | "review"
  | "terminal"
  | "newDoc"
  | "codePatch"
  | "dataAnalysis";

export interface WorkbenchWorkspaceToolTab {
  id: string;
  tool: WorkbenchWorkspaceToolAction;
  title?: string;
}

export interface WorkbenchWorkspaceToolRequest {
  id: string;
  tool: WorkbenchWorkspaceToolAction;
  source?: string;
}

export type WorkbenchPermissionMode = "read_only" | "confirmed_write" | "full_access";

export interface WorkbenchAgentSessionContext {
  sessionId: string;
  threadId: string;
  taskId?: string;
  workspaceRoot: string;
  permissionMode: WorkbenchPermissionMode;
  activeModel: string;
  activeBranch?: string;
  activeTool?: WorkbenchWorkspaceToolAction | null;
  selectedAgentId?: string;
}

export interface WorkbenchFileEntry {
  name: string;
  path: string;
  isDir: boolean;
  thumbnailUrl?: string;
  sizeBytes?: number;
  modifiedAt?: string;
  extension?: string;
  category?: string;
  tags?: string[];
  confidence?: number;
  /** Resource scan root ID this entry belongs to. Used for per-root refresh dedup. */
  sourceRootId?: string;
  /** Canonical resource scan root path this entry belongs to. */
  sourceRootPath?: string;
}

export interface ScanRootItem {
  id: string;
  path: string;
  label?: string;
  kinds: Array<"documents" | "images">;
  enabled: boolean;
  source: "default" | "custom";
}

export interface WorkbenchTrustedComputerApp {
  title: string;
  trustedAt: string;
}

export interface WorkbenchAppEntry {
  name: string;
  path: string;
  iconPath?: string;
  publisher?: string;
  installLocation?: string;
  category?: string;
  tags?: string[];
  confidence?: number;
}

export interface BrowserQuickResult {
  title?: string;
  url: string;
  content?: string;
  screenshotDataUrl?: string;
  loadState?: string;
  sidecarRunning?: boolean;
  canGoBack?: boolean;
  canGoForward?: boolean;
}

export type BrowserQuickAction = "status" | "navigate" | "refresh" | "back" | "forward";

export interface BrowserQuickRequest {
  action: BrowserQuickAction;
  url?: string;
}

export type WorkbenchBrowserWriteApprovalAction = "click" | "type" | "evaluate" | "runTest";

export interface WorkbenchBrowserWriteApprovalPreview {
  approvalId: string;
  sessionId: string;
  toolName: string;
  action: WorkbenchBrowserWriteApprovalAction;
  previewHash: string;
  selector?: string;
  byteCount?: number;
  scriptByteCount?: number;
}

export interface GitPushQuickPreview {
  branch: string;
  upstream: string;
  remoteName: string;
  remoteBranch: string;
  remoteUrl?: string;
  ahead: number;
  behind: number;
  commits: Array<{
    hash: string;
    subject: string;
  }>;
  dryRun: {
    operation: string;
    riskSummary: string;
    reversible: boolean;
    affectedPaths: Array<{
      source: string;
      target: string;
      action: WorkbenchDryRunAction;
      conflict?: string;
    }>;
  };
}

export interface GitPushPlanQuickResult {
  approvalId: string;
  preview: GitPushQuickPreview;
}

export interface GitPushExecutionQuickResult {
  workspacePath: string;
  branch: string;
  upstream: string;
  remoteName: string;
  remoteBranch: string;
  commitCount: number;
  pushed: boolean;
  output: string;
}

export interface GitStageQuickPreview {
  workspaceRoot: string;
  files: Array<{
    path: string;
    indexStatus: string;
    worktreeStatus: string;
    action: WorkbenchDryRunAction;
    contentHash: string;
  }>;
  diffStat: string;
  diff: string;
  dryRun: {
    operation: string;
    riskSummary: string;
    reversible: boolean;
    affectedPaths: Array<{
      source: string;
      target: string;
      action: WorkbenchDryRunAction;
      conflict?: string;
    }>;
  };
}

export interface GitStagePlanQuickResult {
  approvalId: string;
  preview: GitStageQuickPreview;
}

export interface GitStageExecutionQuickResult {
  workspacePath: string;
  stagedPaths: string[];
  fileCount: number;
  staged: boolean;
  output: string;
}

export interface GitCommitQuickPreview {
  workspaceRoot: string;
  branch?: string;
  message: string;
  files: Array<{
    path: string;
    indexStatus: string;
    worktreeStatus: string;
    action: WorkbenchDryRunAction;
    contentHash: string;
  }>;
  diffStat: string;
  diff: string;
  dryRun: {
    operation: string;
    riskSummary: string;
    reversible: boolean;
    affectedPaths: Array<{
      source: string;
      target: string;
      action: WorkbenchDryRunAction;
      conflict?: string;
    }>;
  };
}

export interface GitCommitPlanQuickResult {
  approvalId: string;
  preview: GitCommitQuickPreview;
}

export interface GitCommitExecutionQuickResult {
  workspacePath: string;
  branch?: string;
  commitHash: string;
  subject: string;
  fileCount: number;
  committed: boolean;
  output: string;
}

export interface GitCreatePullRequestQuickPreview {
  workspaceRoot: string;
  provider: string;
  title: string;
  body: string;
  baseBranch: string;
  headBranch: string;
  headCommit: string;
  remoteName?: string;
  remoteUrl?: string;
  draft: boolean;
  dryRun: {
    operation: string;
    riskSummary: string;
    reversible: boolean;
    affectedPaths: Array<{
      source: string;
      target: string;
      action: WorkbenchDryRunAction;
      conflict?: string;
    }>;
  };
}

export interface GitCreatePullRequestPlanQuickResult {
  approvalId: string;
  preview: GitCreatePullRequestQuickPreview;
}

export interface GitCreatePullRequestExecutionQuickResult {
  workspacePath: string;
  provider: string;
  url: string;
  title: string;
  baseBranch: string;
  headBranch: string;
  draft: boolean;
  created: boolean;
  output: string;
}

export interface GitCommentPullRequestQuickPreview {
  workspaceRoot: string;
  provider: string;
  pullRequest: string;
  body: string;
  remoteUrl?: string;
  dryRun: {
    operation: string;
    riskSummary: string;
    reversible: boolean;
    affectedPaths: Array<{
      source: string;
      target: string;
      action: WorkbenchDryRunAction;
      conflict?: string;
    }>;
  };
}

export interface GitCommentPullRequestPlanQuickResult {
  approvalId: string;
  preview: GitCommentPullRequestQuickPreview;
}

export interface GitCommentPullRequestExecutionQuickResult {
  workspacePath: string;
  provider: string;
  pullRequest: string;
  commented: boolean;
  output: string;
}

export interface GitPullRequestQuickSummary {
  number: number;
  title: string;
  state: string;
  url: string;
  author?: string;
  headRefName?: string;
  baseRefName?: string;
  updatedAt?: string;
}

export interface GitPullRequestsQuickResult {
  provider: string;
  unavailableReason?: string;
  pullRequests: GitPullRequestQuickSummary[];
}

export type WorkbenchDryRunAction = "move" | "copy" | "create" | "modify" | "delete" | "overwrite" | "stage" | "push" | "create_pr" | "comment_pr";

export interface ReviewQuickResult {
  changedFiles: string[];
  diffStat: string;
  diff: string;
  workspacePath: string;
  branch?: string;
  upstream?: string;
  upstreamRemote?: string;
  ahead?: number;
  behind?: number;
  remotes?: Array<{
    name: string;
    fetchUrl?: string;
    pushUrl?: string;
  }>;
  pushPreview?: GitPushQuickPreview;
  pullRequests?: GitPullRequestsQuickResult;
}

export interface TerminalQuickResult {
  stdout: string;
  stderr: string;
  exitCode: number | null;
  cwd: string;
  command: string;
}

export interface WorkbenchTerminalSession {
  terminalId: string;
  cwd: string;
  shell: string;
}

export interface WorkbenchTerminalApprovalPreview {
  terminalId?: string;
  workspaceRoot?: string;
  shell?: string;
  inputBytes?: number;
  inputHash?: string;
  sendsEnter?: boolean;
}

export interface WorkbenchTerminalPlanResult {
  approvalId: string;
  toolName: string;
  action: "create" | "input";
  previewHash: string;
  preview: WorkbenchTerminalApprovalPreview;
}

export interface WorkbenchFileSearchResult {
  path: string;
  line?: number;
  preview?: string;
}

export interface WorkbenchBrowserSnapshot {
  url?: string;
  title?: string;
  content?: string;
  screenshotDataUrl?: string;
  loadState?: string;
}

export interface WorkbenchTerminalService {
  planCreate?(
    session: WorkbenchAgentSessionContext,
    terminalId?: string,
  ): Promise<WorkbenchTerminalPlanResult>;
  executeCreate?(
    session: WorkbenchAgentSessionContext,
    plan: WorkbenchTerminalPlanResult,
    cols: number,
    rows: number,
    terminalId?: string,
  ): Promise<WorkbenchTerminalSession>;
  create(
    session: WorkbenchAgentSessionContext,
    cols: number,
    rows: number,
    terminalId?: string,
  ): Promise<WorkbenchTerminalSession>;
  planInput?(
    session: WorkbenchAgentSessionContext,
    terminalId: string,
    data: string,
  ): Promise<WorkbenchTerminalPlanResult>;
  executeInput?(
    session: WorkbenchAgentSessionContext,
    plan: WorkbenchTerminalPlanResult,
    terminalId: string,
    data: string,
  ): Promise<void>;
  input(session: WorkbenchAgentSessionContext, terminalId: string, data: string): Promise<void>;
  resize(terminalId: string, cols: number, rows: number): Promise<void>;
  kill(terminalId: string): Promise<void>;
  subscribe(
    terminalId: string,
    handlers: {
      onOutput: (data: string) => void;
      onExit?: (exitCode: number | null) => void;
      onError?: (message: string) => void;
    },
  ): () => void;
}

export interface WorkbenchFileService {
  list(session: WorkbenchAgentSessionContext, path?: string): Promise<WorkbenchFileEntry[]>;
  search(session: WorkbenchAgentSessionContext, query: string): Promise<WorkbenchFileSearchResult[]>;
  watchStart?(session: WorkbenchAgentSessionContext): Promise<void>;
  watchStop?(session: WorkbenchAgentSessionContext): Promise<void>;
  subscribeChanged?(
    session: WorkbenchAgentSessionContext,
    handler: (paths: string[]) => void,
  ): () => void;
}

export interface JavisWorkbenchProps {
  task: WorkbenchTask;
  draftGoal: string;
  currentWorkspacePath?: string;
  historyEntries?: WorkbenchHistoryEntry[];
  locale?: WorkbenchLocale;
  agentCatalog?: WorkbenchAgentCatalogEntry[];
  modelSettings?: WorkbenchModelSettings;
  modelConfiguration?: WorkbenchModelConfiguration;
  computerUseSettings?: WorkbenchComputerUseSettings;
  computerUseLocalVisionSettings?: WorkbenchComputerUseLocalVisionSettings;
  runtimePreferences?: WorkbenchRuntimePreferences;
  currentGoal?: WorkbenchGoalState | null;
  currentGoalEvents?: WorkbenchGoalEvent[];
  currentGoalEvaluations?: WorkbenchGoalEvaluation[];
  newChatRecommendations?: WorkbenchNewChatRecommendations;
  userProfileMemorySummary?: WorkbenchUserProfileMemorySummary | null;
  agentMemorySummary?: WorkbenchAgentMemorySummary | null;
  recentWorkspacePaths?: string[];
  activeView?: ActiveView;
  activeHistoryEntryId?: string;
  scheduledTasks?: WorkbenchScheduledTask[];
  skillEntries?: WorkbenchSkillEntry[];
  skillTranslationStatus?: "idle" | "translating" | "error";
  skillTranslationError?: string | null;
  skillSearchResults?: WorkbenchSkillSearchResult[];
  skillSearchStatus?: "idle" | "searching" | "error";
  skillMarketSuggestions?: WorkbenchSkillSuggestion[];
  skillMarketSuggestionStatus?: "idle" | "refreshing" | "error";
  mcpConfigError?: string | null;
  /** Custom sidebar navigation items. Merged with built-in defaults. */
  sidebarNavItems?: SidebarNavItem[];
  installedApps?: WorkbenchAppEntry[];
  userDocuments?: WorkbenchFileEntry[];
  userImages?: WorkbenchFileEntry[];
  computerEntries?: WorkbenchFileEntry[];
  trustedComputerApps?: WorkbenchTrustedComputerApp[];
  computerPath?: string;
  mountRoots?: { name: string; path: string }[];
  isTaskActive?: boolean;
  appsLoading?: boolean;
  docsLoading?: boolean;
  imagesLoading?: boolean;
  computerLoading?: boolean;
  appsError?: string;
  docsError?: string;
  imagesError?: string;
  computerError?: string;
  // ── File classification ─────────────────────────────────────────
  scanning?: boolean;
  scanProgress?: WorkbenchProgress;
  appsProgress?: WorkbenchProgress;
  docsProgress?: WorkbenchProgress;
  imagesProgress?: WorkbenchProgress;
  classifying?: boolean;
  classifyProgress?: WorkbenchProgress & { completed?: number };
  classifyError?: string;
  appsClassifying?: boolean;
  appsClassifyProgress?: WorkbenchProgress & { completed?: number };
  appsClassifyError?: string;
  categoryStats?: { category: string; count: number }[];
  appCategoryStats?: { category: string; count: number }[];
  /** Resource scan roots (default + custom) for docs/images views. */
  resourceScanRoots?: ScanRootItem[];
  onRefreshScan?: () => void;
  onRefreshResourceRoots?: (kind: "documents" | "images") => void;
  onClassifyDocuments?: () => void;
  onClassifyApps?: () => void;
  onCancelClassify?: () => void;
  onCancelClassifyApps?: () => void;
  onToggleScanRoot?: (id: string, enabled: boolean) => void;
  onRemoveScanRoot?: (id: string) => void;
  onAddScanRoot?: (path: string, kinds: Array<"documents" | "images">, label?: string) => void;
  onRefreshScanRoot?: (id: string) => void;
  onDraftGoalChange: (nextGoal: string) => void;
  onPauseGoal?: () => void;
  onResumeGoal?: () => void;
  onCompleteGoal?: () => void;
  onClearGoal?: () => void;
  onDeleteHistoryEntry?: (id: string) => void;
  onDeleteRecentWorkspacePath?: (path: string) => void;
  onBrowseWorkspacePath?: () => void;
  onModelSettingsChange?: (settings: WorkbenchModelSettings) => void;
  onTestModelConnection?: (settings: WorkbenchModelSettings) => Promise<string | void>;
  onModelConfigurationChange?: (config: WorkbenchModelConfiguration) => void;
  onComputerUseSettingsChange?: (settings: WorkbenchComputerUseSettings) => void;
  onComputerUseLocalVisionSettingsChange?: (settings: WorkbenchComputerUseLocalVisionSettings) => void;
  onRuntimePreferencesChange?: (preferences: WorkbenchRuntimePreferences) => void;
  onRebuildUserProfileMemory?: () => void;
  onClearUserProfileMemory?: () => void;
  onAgentMemoryEnabledChange?: (enabled: boolean) => void;
  onClearAgentMemory?: () => void;
  onClearWorkspaceAgentMemory?: () => void;
  onDeleteAgentMemoryFact?: (id: string) => void;
  onReadAgentStyle?: (kind: string) => Promise<WorkbenchAgentStyleState>;
  onSaveAgentStyle?: (kind: string, content: string) => Promise<WorkbenchAgentStyleState | void>;
  onResetAgentStyle?: (kind: string) => Promise<WorkbenchAgentStyleState | void>;
  onSaveProviderApiKey?: (keyReference: string, apiKey: string) => Promise<void>;
  onFetchProviderModels?: (params: {
    provider: string;
    baseUrl: string;
    apiKey: string;
    apiType: string;
    keyReference: string;
    modelListMode: "openai" | "anthropic" | "unsupported";
  }) => Promise<string[]>;
  /** External provider catalog from @javis/core. When provided, replaces the built-in catalog. */
  providerCatalog?: readonly ProviderCatalogEntry[];
  /** Resolve default capabilities for a provider from its registered adapter. */
  getProviderCapabilities?: (provider: string) => ProviderCapabilities;
  terminalService?: WorkbenchTerminalService;
  fileService?: WorkbenchFileService;
  onSelectHistoryEntry?: (id: string) => void;
  onUseWorkspacePath?: (path: string) => void;
  onWorkspacePathChange?: (path: string) => void;
  onPermissionDecision?: (decision: WorkbenchPermissionDecision) => void;
  onAskUserAnswer?: (answer: string) => void;
  onRetryTask?: () => void;
  onStopTask?: () => void;
  onEmergencyStopTask?: () => void;
  onConversationMessagesChange?: (taskId: string | undefined, messages: WorkbenchChatMessage[]) => void;
  /** When user clicks an agent summary card in the chat, selected agent ID + open right sidebar. */
  onSelectAgent?: (agentId: string) => void;
  onSubmitGoal: (
    goal?: string,
    workspacePath?: string,
    scheduledTaskId?: string,
    attachments?: File[],
    imageDataUrls?: string[],
    options?: WorkbenchSubmitGoalOptions,
  ) => void;
  onTranslateSkillsToChinese?: () => void;
  onSearchSkillMarket?: (
    query: string,
    source: WorkbenchSkillSearchSource,
    kind: WorkbenchSkillSearchKind,
  ) => void;
  onRefreshSkillMarketSuggestions?: (
    source: WorkbenchSkillSearchSource,
    kind: WorkbenchSkillSearchKind,
  ) => void;
  onToggleSkillEnabled?: (id: string, enabled: boolean) => void;
  onDeleteSkill?: (id: string) => void;
  onDisableAllSkills?: () => void;
  onDeleteAllSkills?: () => void;
  onInstallSkillMarketResult?: (result: WorkbenchSkillSearchResult) => void;
  onOpenDetail?: (detail: WorkbenchDetailItem) => void;
  onOpenUrl?: (url: string) => void;
  onOpenWorkspaceTool?: (action: WorkbenchWorkspaceToolAction) => void;
  onChangeActiveView?: (view: ActiveView) => void;
  onSelectComposeMode?: (mode: "chat" | "project") => void;
  activeComposeMode?: "chat" | "project";
  onToggleScheduledTask?: (id: string) => void;
  onCreateScheduledTask?: (draft: WorkbenchScheduledTaskDraft) => void;
  onDeleteScheduledTask?: (id: string) => void;
  onRefreshApps?: () => void;
  onUpdateAppCategory?: (path: string, category: string) => void;
  onUpdateFileCategory?: (path: string, category: string) => void;
  onRefreshDocuments?: () => void;
  onRefreshImages?: () => void;
  onNavigateDirectory?: (path: string) => void;
  onListDirectory?: (path: string) => Promise<WorkbenchFileEntry[]>;
  onOpenFile?: (path: string) => void;
  onRemoveTrustedComputerApp?: (title: string) => void;
  onSidebarWidthChange?: (width: number) => void;
  onActiveViewChange?: (view: ActiveView) => void;
  onSidebarOpenChange?: (open: boolean) => void;
  onActivityOpenChange?: (open: boolean) => void;
  onInspectorOpenChange?: (open: boolean) => void;
  onActivityHeightChange?: (height: number) => void;
  /** Open workspace tool tabs in the inspector. Last tab is active. */
  openTabs?: WorkbenchWorkspaceToolAction[];
  workspaceToolTabs?: WorkbenchWorkspaceToolTab[];
  /** One-shot request from the host/runtime to open and focus a workspace tool. */
  workspaceToolRequest?: WorkbenchWorkspaceToolRequest | null;
  onActiveToolChange?: (tool: WorkbenchWorkspaceToolAction | null) => void;
  /** Browser tool — navigate to URL, returns page metadata. */
  onQuickActionBrowser?: (session: WorkbenchAgentSessionContext, request: string | BrowserQuickRequest) => Promise<BrowserQuickResult>;
  pendingBrowserWriteApproval?: WorkbenchBrowserWriteApprovalPreview | null;
  onApproveBrowserWrite?: (session: WorkbenchAgentSessionContext, approvalId: string) => Promise<void>;
  onDenyBrowserWrite?: (session: WorkbenchAgentSessionContext, approvalId: string) => Promise<void>;
  /** Review tool — run git diff and return review data. */
  onQuickActionReview?: (session: WorkbenchAgentSessionContext) => Promise<ReviewQuickResult>;
  /** Git push tool: create an approval-bound push preview. */
  onQuickActionGitPushPlan?: (session: WorkbenchAgentSessionContext) => Promise<GitPushPlanQuickResult>;
  /** Git push tool: approve and execute the current push preview. */
  onQuickActionGitPushExecute?: (session: WorkbenchAgentSessionContext, approvalId: string) => Promise<GitPushExecutionQuickResult>;
  /** Git push tool: mark a prepared push approval as cancelled/denied. */
  onQuickActionGitPushCancel?: (session: WorkbenchAgentSessionContext, approvalId: string) => Promise<void>;
  /** Git stage tool: create an approval-bound selected-files stage preview. */
  onQuickActionGitStagePlan?: (session: WorkbenchAgentSessionContext, paths: string[]) => Promise<GitStagePlanQuickResult>;
  /** Git stage tool: approve and execute the current selected-files stage preview. */
  onQuickActionGitStageExecute?: (session: WorkbenchAgentSessionContext, approvalId: string, paths: string[]) => Promise<GitStageExecutionQuickResult>;
  /** Git stage tool: mark a prepared stage approval as cancelled/denied. */
  onQuickActionGitStageCancel?: (session: WorkbenchAgentSessionContext, approvalId: string) => Promise<void>;
  /** Git commit tool: create an approval-bound commit preview for current changes. */
  onQuickActionGitCommitPlan?: (session: WorkbenchAgentSessionContext, message: string) => Promise<GitCommitPlanQuickResult>;
  /** Git commit tool: approve and execute the current commit preview. */
  onQuickActionGitCommitExecute?: (session: WorkbenchAgentSessionContext, approvalId: string, message: string) => Promise<GitCommitExecutionQuickResult>;
  /** Git commit tool: mark a prepared commit approval as cancelled/denied. */
  onQuickActionGitCommitCancel?: (session: WorkbenchAgentSessionContext, approvalId: string) => Promise<void>;
  /** Git pull request tool: create an approval-bound draft PR preview. */
  onQuickActionGitCreatePullRequestPlan?: (
    session: WorkbenchAgentSessionContext,
    request: { title: string; body?: string; baseBranch: string; draft?: boolean },
  ) => Promise<GitCreatePullRequestPlanQuickResult>;
  /** Git pull request tool: approve and execute the current draft PR preview. */
  onQuickActionGitCreatePullRequestExecute?: (
    session: WorkbenchAgentSessionContext,
    approvalId: string,
    request: { title: string; body?: string; baseBranch: string; draft?: boolean },
  ) => Promise<GitCreatePullRequestExecutionQuickResult>;
  /** Git pull request tool: mark a prepared PR approval as cancelled/denied. */
  onQuickActionGitCreatePullRequestCancel?: (session: WorkbenchAgentSessionContext, approvalId: string) => Promise<void>;
  /** Git pull request comment tool: create an approval-bound PR comment preview. */
  onQuickActionGitCommentPullRequestPlan?: (
    session: WorkbenchAgentSessionContext,
    request: { pullRequest: string; body: string },
  ) => Promise<GitCommentPullRequestPlanQuickResult>;
  /** Git pull request comment tool: approve and execute the current PR comment preview. */
  onQuickActionGitCommentPullRequestExecute?: (
    session: WorkbenchAgentSessionContext,
    approvalId: string,
    request: { pullRequest: string; body: string },
  ) => Promise<GitCommentPullRequestExecutionQuickResult>;
  /** Git pull request comment tool: mark a prepared PR comment approval as cancelled/denied. */
  onQuickActionGitCommentPullRequestCancel?: (session: WorkbenchAgentSessionContext, approvalId: string) => Promise<void>;
  /** Terminal tool — run a shell command and return output. */
  onQuickActionTerminal?: (session: WorkbenchAgentSessionContext, command: string) => Promise<TerminalQuickResult>;
  /** SideChat tool — send a message and get AI response. */
  onQuickActionSideChat?: (session: WorkbenchAgentSessionContext, message: string) => Promise<string>;
  initialSidebarWidth?: number;
  initialActivityHeight?: number;
  initialIsSidebarOpen?: boolean;
  initialIsActivityOpen?: boolean;
  initialIsInspectorOpen?: boolean;
  systemResources?: WorkbenchSystemResources;
}

export interface WorkbenchLocale {
  categoryLabels?: Record<string, string>;
  labels: {
    activeTask: string;
    activityLog: string;
    addPhotosAndFiles: string;
    addedAttachments: string;
    accountSettings: string;
    aiModeSettings: string;
    apps: string;
    askUserQuestion: string;
    automatedTasks: string;
    collapseActivityLog: string;
    collapseSidebar: string;
    agentContextInspector: string;
    agentGraph: string;
    agentStates: string;
    collapseInspector: string;
    approve: string;
    approveOnce: string;
    allowTask: string;
    alwaysAllow: string;
    allLevels: string;
    denyPermission: string;
    fullAccess: string;
    requestApproval: string;
    approvalRequested: string;
    commandResults: string;
    commander: string;
    codeReview: string;
    changedFiles: string;
    closeSettings: string;
    clearLogs: string;
    completed: string;
    currentTask: string;
    deny: string;
    deleteHistoryEntry: string;
    documents: string;
    emptyOutput: string;
    executionTimeline: string;
    expandActivityLog: string;
    expandSidebar: string;
    expandInspector: string;
    failed: string;
    layoutPresetChat: string;
    layoutPresetExpanded: string;
    layoutPresetFocus: string;
    layoutPresets: string;
    fileOrganizationResult: string;
    filterLogs: string;
    failedRecoveryTitle: string;
    failedRecoveryMessage: string;
    gallery: string;
    generalSettings: string;
    history: string;
    historyEmpty: string;
    historyEmptyGroup: string;
    historyNoMatches: string;
    expandHistoryGroup: string;
    hideProcessDetails: string;
    localKnowledgeBase: string;
    logLevelFilter: string;
    mainThread: string;
    manualSourceFallbackTitle: string;
    manualSourceFallbackMessage: string;
    markdownDocuments: string;
    models: string;
    modelProvider?: string;
    modelName?: string;
    modelApiKey?: string;
    modelBaseUrl?: string;
    modelSettingsDescription?: string;
    modelBackendUnavailable?: string;
    modified: string;
    moreInputOptions: string;
    newChat: string;
    newChatTitle: string;
    chatNewChatTitle: string;
    chat: string;
    office: string;
    packageScript: string;
    plan: string;
    planMode: string;
    plugins: string;
    projectInspection: string;
    project: string;
    processDetails: string;
    projects: string;
    profileName: string;
    researchReport: string;
    researchSources: string;
    retryTask: string;
    running: string;
    send: string;
    stopTask: string;
    submitAnswer: string;
    searchPlaceholder: string;
    settings: string;
    settingsPlaceholder: string;
    showProcessDetails: string;
    skillMarket: string;
    source: string;
    status: string;
    taskInput: string;
    taskInputPlaceholder: string;
    chatTaskInputPlaceholder: string;
    testCheck: string;
    thisComputer: string;
    tokenUsage: string;
    tokenInput: string;
    tokenOutput: string;
    tokenCalls: string;
    trustedComputerApps: string;
    removeTrustedApp: string;
    contextWindow: string;
    contextUsed: string;
    contextRemaining: string;
    contextBreakdown: string;
    noModelCalls: string;
    unknown: string;
    unknownManager: string;
    unverified: string;
    user: string;
    verifier: string;
    workspaceNavigation: string;
    workspaceControls: string;
    waiting: string;
    sidebarResize: string;
    browseWorkspace: string;
    currentWorkspace: string;
    recentWorkspaces: string;
    removeAttachment: string;
    removeWorkspace: string;
    useWorkspace: string;
    workspaceBrowseError: string;
    workspacePathPlaceholder: string;
    automatedTasksTitle: string;
    scheduledTaskEnabled: string;
    scheduledTaskDisabled: string;
    scheduledTaskNextRun: string;
    scheduledTaskLastRun: string;
    scheduledTaskName: string;
    scheduledTaskGoal: string;
    scheduledTaskScheduleType: string;
    scheduledTaskScheduleValue: string;
    scheduledTaskDaily: string;
    scheduledTaskWeekly: string;
    scheduledTaskInterval: string;
    scheduledTaskOnce: string;
    createScheduledTask: string;
    skillMarketTitle: string;
    skillCategoryTool: string;
    skillCategoryAgent: string;
    skillCategoryMcp: string;
    noMcpConfig: string;
    mcpLoadError?: string;
    skillUiFeatureLabel: string;
    privacySecuritySettings: string;
    aboutFeedbackSettings: string;
    appsTitle: string;
    documentsTitle: string;
    galleryTitle: string;
    computerTitle: string;
    fileExplorerBreadcrumb: string;
    fileExplorerEmpty: string;
    scanInProgress: string;
    scanComplete: string;
    noAppsFound: string;
    noDocumentsFound: string;
    noImagesFound: string;
    noScheduledTasks: string;
    scanFailed: string;
    retry: string;
    unknownView: string;
    kbDocRecognition: string;
    kbCourseware: string;
    kbBooks: string;
    kbPapers: string;
    kbImageRecognition: string;
    kbPeopleImpressions: string;
    kbFootprintLocations: string;
    kbTimelineGallery: string;
    kbSystemDrive: string;
    kbDriveE: string;
    kbDriveF: string;
    kbDriveG: string;
    classifyButton: string;
    cancelClassify: string;
    classifyProgress: string;
    classifyFailed: string;
    allCategories: string;
    categoryBadge: string;
    confidenceLabel: string;
  };
  phrases?: Record<string, string>;
}
