import type { UserProfileMemoryFactKind } from "./user-profile-memory";

export interface TopicRule {
  tag: string;
  kind: UserProfileMemoryFactKind;
  zhText: string;
  enText: string;
  keywords: string[];
  promptZh: string;
  promptEn: string;
}

export const TOPIC_RULES: TopicRule[] = [
  {
    tag: "workbench",
    kind: "current_focus",
    zhText: "用户最近在推进 Javis workbench 的新聊天入口、工作区面板和任务上下文体验。",
    enText: "The user has recently been improving the Javis workbench, new-chat entry, workspace panels, and task context experience.",
    keywords: [
      "workbench",
      "工作台",
      "工作区",
      "新聊天",
      "推荐栏",
      "recommendation bar",
      "new chat",
      "WorkspaceToolPanels",
      "JavisWorkbench",
      "ChatView",
      "NewChat",
    ],
    promptZh: "继续优化 Javis workbench 的新聊天推荐栏和工作区体验，检查推荐是否贴近最近任务上下文。",
    promptEn: "Continue improving the Javis workbench new-chat recommendation bar and workspace experience, checking that recommendations match recent task context.",
  },
  {
    tag: "ui",
    kind: "current_focus",
    zhText: "用户最近重点关注 Javis 的 UI 美化、布局一致性、图标尺寸和视觉还原。",
    enText: "The user has recently focused on Javis UI polish, layout consistency, icon sizing, and visual fidelity.",
    keywords: [
      "UI",
      "界面",
      "美化",
      "视觉",
      "概念图",
      "侧边栏",
      "日志栏",
      "图标",
      "按钮",
      "布局",
      "宽度",
      "polish",
      "icon",
      "layout",
    ],
    promptZh: "对照最近的 UI 美化方向继续打磨 Javis 界面，重点检查推荐栏、侧边栏、日志区、图标尺寸和一致性。",
    promptEn: "Keep polishing the Javis UI around the recent visual direction, focusing on recommendations, sidebars, activity logs, icon sizing, and consistency.",
  },
  {
    tag: "computer-use",
    kind: "current_focus",
    zhText: "用户最近在改造 computer use：桌面自动化、浏览器/屏幕工具、审批和执行循环。",
    enText: "The user has recently been reworking computer use: desktop automation, browser/screen tools, approvals, and the action loop.",
    keywords: [
      "computer use",
      "computer-use",
      "computer_use",
      "桌面自动化",
      "电脑操作",
      "屏幕",
      "截图",
      "浏览器",
      "点击",
      "输入",
      "审批",
      "approval",
      "runComputerUseLoop",
      "ComputerUse",
      "browser",
      "screen",
    ],
    promptZh: "继续完善 computer use 改造，优先检查桌面自动化路由、审批、浏览器/屏幕工具和执行循环的测试覆盖。",
    promptEn: "Continue hardening computer use, prioritizing desktop automation routing, approvals, browser/screen tools, and action-loop tests.",
  },
  {
    tag: "memory",
    kind: "current_focus",
    zhText: "用户正在推进基于历史会话和当前项目上下文的用户侧写记忆与新聊天推荐系统。",
    enText: "The user is building profile memory and new-chat recommendations from history and current workspace context.",
    keywords: [
      "记忆",
      "侧写",
      "画像",
      "推荐",
      "用户偏好",
      "user-profile-memory",
      "user-profile-rules",
      "user-profile-recommendation-engine",
      "createNewChatRecommendations",
      "new-chat recommendations",
      "UserProfileMemory",
      "RecommendationEngine",
      "recommendation",
      "memory",
      "profile",
      "persona",
    ],
    promptZh: "继续完善 user-profile-memory 和 user-profile-rules 的提取逻辑，减少泛化 fallback，并补测试验证推荐是否更贴近最近工作。",
    promptEn: "Continue refining user-profile-memory and user-profile-rules extraction, reduce generic fallback, and add tests proving recommendations match recent work.",
  },
  {
    tag: "implementation",
    kind: "work_pattern",
    zhText: "用户偏好把需求直接推进到可运行、可验证的代码实现。",
    enText: "The user prefers turning requirements into runnable and verified code changes.",
    keywords: ["实现", "改造", "补齐", "修复", "代码", "落地", "生产级", "build", "test", "tsx", "typescript", "rust"],
    promptZh: "把当前需求拆成可落地的实现步骤，直接修改代码，并说明改动点和验证结果。",
    promptEn: "Break the current request into implementable steps, update the code, and report changes and verification.",
  },
  {
    tag: "verification",
    kind: "work_pattern",
    zhText: "用户重视构建、测试和界面检查，希望每轮改动有明确验证结果。",
    enText: "The user values build, test, and UI checks with clear verification results for each change.",
    keywords: ["验证", "测试", "检查", "通过", "失败", "覆盖", "vitest", "playwright", "typecheck", "lint"],
    promptZh: "运行当前项目可用的验证命令，确认构建、测试和关键界面状态是否正常。",
    promptEn: "Run available verification commands and report build, test, and key UI status.",
  },
  {
    tag: "local-knowledge",
    kind: "current_focus",
    zhText: "用户关注本地知识库、应用、文档、图库和项目资料的组织与使用。",
    enText: "The user cares about organizing and using local apps, documents, galleries, and project knowledge.",
    keywords: ["本地知识库", "应用", "文档", "图库", "项目资料", "文件", "570Icons", "local knowledge"],
    promptZh: "梳理当前工作区的应用、文档和项目资料，生成可用于推荐和检索的本地知识上下文。",
    promptEn: "Organize apps, documents, and project material in the current workspace into local context for recommendations and retrieval.",
  },
  {
    tag: "research",
    kind: "work_pattern",
    zhText: "用户会参考 study 项目中的已有架构，再迁移适合 Javis 的机制。",
    enText: "The user compares study projects and migrates useful architecture patterns into Javis.",
    keywords: ["study", "参考", "其他项目", "Proma", "openhanako", "TG-HELPER", "调研", "研究", "架构"],
    promptZh: "继续对照 study 里的 Proma、openhanako 和 TG-HELPER，总结哪些机制适合迁移到 Javis。",
    promptEn: "Compare Proma, openhanako, and TG-HELPER under study and summarize which mechanisms should move into Javis.",
  },
];
