import type { ToolDescriptor } from "./types";

const DISABLED_BROWSER_WRITE_TOOL_NAMES = new Set([
  "browser.upload",
]);

export function isDisabledBrowserWriteToolName(toolName: string): boolean {
  return DISABLED_BROWSER_WRITE_TOOL_NAMES.has(toolName);
}

export const initialToolDescriptors: ToolDescriptor[] = [
  // ── Commander ──────────────────────────────────────────────────────────
  {
    name: "commander.plan",
    permissionLevel: "read",
    summary: "Analyze a user goal and produce a task plan with assigned agent steps.",
    capabilityTags: ["planning"],
    ownerAgentKinds: ["commander"],
  },
  {
    name: "commander.synthesize",
    permissionLevel: "read",
    summary: "Synthesize collected evidence from all workflow steps into a user-facing conclusion.",
    capabilityTags: ["synthesis"],
    ownerAgentKinds: ["commander"],
  },
  {
    name: "commander.askUser",
    permissionLevel: "read",
    summary: "Ask the user a clarifying question when the goal is ambiguous or information is missing.",
    capabilityTags: ["clarification"],
    ownerAgentKinds: ["commander"],
  },

  // ── Verifier ───────────────────────────────────────────────────────────
  {
    name: "verifier.check",
    permissionLevel: "read",
    summary: "Check collected evidence against success criteria and produce a verdict.",
    capabilityTags: ["evidence_check"],
    ownerAgentKinds: ["verifier"],
  },

  // ── File ───────────────────────────────────────────────────────────────
  {
    name: "file.scanMarkdownDocuments",
    permissionLevel: "read",
    summary: "Scan Markdown documents inside the active workspace.",
    capabilityTags: ["file_scan"],
    ownerAgentKinds: ["file", "verifier", "doc-updater", "explorer"],
  },
  {
    name: "file.scanUserDocuments",
    permissionLevel: "read",
    summary: "Scan user document files across Desktop, Documents, and Downloads.",
    capabilityTags: ["file_scan"],
    ownerAgentKinds: ["file", "doc-updater"],
  },
  {
    name: "file.classifyDocuments",
    permissionLevel: "read",
    summary: "Classify scanned local documents into predefined categories using AI.",
    capabilityTags: ["document_classify"],
    ownerAgentKinds: ["file", "doc-updater"],
  },
  {
    name: "file.planPdfOrganization",
    permissionLevel: "preview",
    summary: "Create a dry-run plan for organizing PDF files without moving them.",
    capabilityTags: ["file_scan"],
    ownerAgentKinds: ["file"],
  },
  {
    name: "file.executePdfOrganization",
    permissionLevel: "confirmed_write",
    writeRiskLevel: "risky",
    summary: "Move PDF files exactly as listed in an approved dry-run plan.",
    capabilityTags: ["file_execute"],
    ownerAgentKinds: ["file"],
  },

  // ── Shell ──────────────────────────────────────────────────────────────
  {
    name: "file.planWriteText",
    permissionLevel: "preview",
    summary: "Create a dry-run plan for writing text content to a file.",
    capabilityTags: ["file_scan"],
    ownerAgentKinds: ["file", "doc-updater"],
  },
  {
    name: "file.writeText",
    permissionLevel: "confirmed_write",
    writeRiskLevel: "safe",
    summary: "Write approved text content to a target file.",
    capabilityTags: ["file_execute"],
    ownerAgentKinds: ["file", "doc-updater"],
  },
  {
    name: "shell.runReadOnlyCommand",
    permissionLevel: "read",
    summary: "Run an allowlisted read-only shell command in the workspace.",
    capabilityTags: ["shell_readonly"],
    ownerAgentKinds: [
      "shell",
      "code",
      "verifier",
      "language-reviewer",
      "security-reviewer",
      "build-fix",
      "test-runner",
      "doc-updater",
      "explorer",
      "perf-analyzer",
      "refactor",
    ],
  },

  // ── Code ───────────────────────────────────────────────────────────────
  {
    name: "code.inspectRepository",
    permissionLevel: "preview",
    summary: "Collect changed files, diff summary, and diff preview without applying edits.",
    capabilityTags: ["git_inspect"],
    ownerAgentKinds: [
      "code",
      "research",
      "language-reviewer",
      "security-reviewer",
      "build-fix",
      "test-runner",
      "doc-updater",
      "explorer",
      "perf-analyzer",
      "refactor",
    ],
  },
  {
    name: "code.searchRepository",
    permissionLevel: "read",
    summary: "Search the current repository with structured fallback attempts, clustering, key files, and evidence gaps.",
    capabilityTags: ["code_search"],
    ownerAgentKinds: [
      "code",
      "research",
      "language-reviewer",
      "security-reviewer",
      "build-fix",
      "test-runner",
      "doc-updater",
      "explorer",
      "perf-analyzer",
      "refactor",
    ],
  },
  {
    name: "code.traceCallChain",
    permissionLevel: "read",
    summary: "Trace a repository call/reference chain from a generic target and optional entrypoints, returning evidence nodes, edges, module-link hints, key files, and confirmation gaps.",
    capabilityTags: ["code_trace"],
    ownerAgentKinds: [
      "code",
      "language-reviewer",
      "security-reviewer",
      "build-fix",
      "test-runner",
      "explorer",
      "perf-analyzer",
      "refactor",
    ],
  },
  {
    name: "code.proposeEdit",
    permissionLevel: "preview",
    summary: "Produce a patch proposal for user review without modifying files.",
    capabilityTags: ["code_propose"],
    ownerAgentKinds: ["code", "build-fix", "doc-updater", "refactor"],
  },
  {
    name: "code.applyProposedEdit",
    permissionLevel: "confirmed_write",
    writeRiskLevel: "risky",
    summary: "Apply only the approved Code Agent patch proposal.",
    capabilityTags: ["code_apply"],
    ownerAgentKinds: ["code", "build-fix", "doc-updater", "refactor"],
  },
  {
    name: "git.stageFiles",
    permissionLevel: "confirmed_write",
    writeRiskLevel: "risky",
    summary: "Stage explicitly selected workspace files in the Git index after approval.",
    capabilityTags: ["git_stage"],
    ownerAgentKinds: ["code"],
  },
  {
    name: "git.createCommit",
    permissionLevel: "confirmed_write",
    writeRiskLevel: "risky",
    summary: "Stage current or explicitly selected workspace changes and create a local Git commit after approval.",
    capabilityTags: ["git_commit"],
    ownerAgentKinds: ["code"],
  },
  {
    name: "git.createPullRequest",
    permissionLevel: "confirmed_write",
    writeRiskLevel: "risky",
    summary: "Create a draft GitHub pull request from the current branch after approval; requires title and baseBranch, with optional body and draft.",
    capabilityTags: ["git_pr_create"],
    ownerAgentKinds: ["code"],
  },
  {
    name: "git.commentPullRequest",
    permissionLevel: "confirmed_write",
    writeRiskLevel: "risky",
    summary: "Add a comment to a GitHub pull request after approval; requires pullRequest and body.",
    capabilityTags: ["git_pr_comment"],
    ownerAgentKinds: ["code"],
  },

  // ── Research ──────────────────────────────────────────────────────────
  {
    name: "web.search",
    permissionLevel: "read",
    summary: "Search public web sources through a configured provider.",
    capabilityTags: ["web_search"],
    ownerAgentKinds: ["research"],
  },
  {
    name: "web.fetchSource",
    permissionLevel: "read",
    summary: "Fetch a user-provided public web source URL.",
    capabilityTags: ["web_fetch"],
    ownerAgentKinds: ["research"],
  },
  {
    name: "trend.fetchHotList",
    permissionLevel: "read",
    summary: "Fetch a structured public hot/trending list from a supported provider such as Weibo, with item count and freshness metadata.",
    capabilityTags: ["trend_fetch", "web_fetch"],
    ownerAgentKinds: ["research"],
  },
  {
    name: "memory.search",
    permissionLevel: "read",
    summary: "Search local Agent memory facts by query, tags, kind, and scope. Does not create or edit facts; may update local access metadata.",
    capabilityTags: ["memory_search"],
    ownerAgentKinds: ["commander", "workspace"],
  },

  // ── Computer ──────────────────────────────────────────────────────────
  {
    name: "file.scanUserImages",
    permissionLevel: "read",
    summary: "Scan user image files across common user directories.",
    capabilityTags: ["image_scan"],
    ownerAgentKinds: ["computer"],
  },
  {
    name: "file.scanInstalledApps",
    permissionLevel: "read",
    summary: "Scan installed desktop applications from Start Menu and Desktop shortcuts.",
    capabilityTags: ["local_search"],
    ownerAgentKinds: ["computer"],
  },
  {
    name: "computer.searchLocalDocuments",
    permissionLevel: "read",
    summary: "Search indexed local files by name, keyword, and metadata.",
    capabilityTags: ["local_search"],
    ownerAgentKinds: ["computer"],
  },
  {
    name: "computer.listDirectory",
    permissionLevel: "read",
    summary: "List direct children of a directory for file explorer browsing. Requires toolInput.path as a non-empty string.",
    capabilityTags: ["directory_list"],
    ownerAgentKinds: ["computer"],
  },
  {
    name: "computer.openPath",
    permissionLevel: "read",
    summary: "Open a file or directory path in the native OS shell. Requires toolInput.path as a non-empty string.",
    capabilityTags: ["local_search"],
    ownerAgentKinds: ["computer"],
  },
  {
    name: "computer.screenshot",
    permissionLevel: "read",
    summary: "Capture the current desktop, a specific window, or a cropped region as a PNG screenshot.",
    capabilityTags: ["desktop_screenshot"],
    ownerAgentKinds: ["computer"],
  },
  {
    name: "computer.listWindows",
    permissionLevel: "read",
    summary: "Enumerate all visible windows with titles, handles, and screen positions.",
    capabilityTags: ["desktop_list_windows"],
    ownerAgentKinds: ["computer"],
  },
  {
    name: "computer.inspectUi",
    permissionLevel: "read",
    summary: "Inspect a window's UI Automation control tree without moving the mouse.",
    capabilityTags: ["desktop_ui_tree"],
    ownerAgentKinds: ["computer"],
  },
  {
    name: "computer.focusWindow",
    permissionLevel: "confirmed_write",
    writeRiskLevel: "safe",
    summary: "Bring a specific window to the foreground by handle. Requires user approval.",
    capabilityTags: ["desktop_focus"],
    ownerAgentKinds: ["computer"],
  },
  {
    name: "computer.moveMouse",
    permissionLevel: "confirmed_write",
    writeRiskLevel: "safe",
    summary: "Move the mouse cursor to absolute screen coordinates. Requires user approval.",
    capabilityTags: ["desktop_input"],
    ownerAgentKinds: ["computer"],
  },
  {
    name: "computer.click",
    permissionLevel: "confirmed_write",
    writeRiskLevel: "dangerous",
    summary: "Click at absolute screen coordinates. Requires user approval.",
    capabilityTags: ["desktop_input"],
    ownerAgentKinds: ["computer"],
  },
  {
    name: "computer.type",
    permissionLevel: "confirmed_write",
    writeRiskLevel: "dangerous",
    summary: "Type text via keyboard input simulation. Requires user approval.",
    capabilityTags: ["desktop_input"],
    ownerAgentKinds: ["computer"],
  },
  {
    name: "computer.keyCombo",
    permissionLevel: "confirmed_write",
    writeRiskLevel: "dangerous",
    summary: "Press a key combination (e.g. Ctrl+C). Requires user approval and allowlist check.",
    capabilityTags: ["desktop_input"],
    ownerAgentKinds: ["computer"],
  },
  {
    name: "computer.scroll",
    permissionLevel: "confirmed_write",
    writeRiskLevel: "safe",
    summary: "Scroll at absolute screen coordinates. Requires user approval.",
    capabilityTags: ["desktop_input"],
    ownerAgentKinds: ["computer"],
  },
  {
    name: "computer.invokeUi",
    permissionLevel: "confirmed_write",
    writeRiskLevel: "risky",
    summary: "Invoke a UI Automation control by selector without moving the physical mouse. Requires user approval.",
    capabilityTags: ["desktop_ui_input"],
    ownerAgentKinds: ["computer"],
  },
  {
    name: "computer.setUiValue",
    permissionLevel: "confirmed_write",
    writeRiskLevel: "risky",
    summary: "Set a UI Automation value by selector without moving the physical mouse. Requires user approval.",
    capabilityTags: ["desktop_ui_input"],
    ownerAgentKinds: ["computer"],
  },
  {
    name: "computer.wait",
    permissionLevel: "read",
    summary: "Wait for a specified duration (max 10 seconds).",
    capabilityTags: ["desktop_screenshot"],
    ownerAgentKinds: ["computer"],
  },

  // ── Scheduler ─────────────────────────────────────────────────────────
  {
    name: "scheduler.createTask",
    permissionLevel: "confirmed_write",
    writeRiskLevel: "safe",
    summary: "Create a durable local scheduled task or reminder.",
    capabilityTags: ["schedule_create"],
    ownerAgentKinds: ["scheduler"],
  },
  // ── Workspace ─────────────────────────────────────────────────────────
  {
    name: "workspace.list",
    permissionLevel: "read",
    summary: "List installed custom workspace definitions.",
    capabilityTags: ["workspace_list"],
    ownerAgentKinds: ["workspace"],
  },
  {
    name: "workspace.scaffold",
    permissionLevel: "preview",
    summary: "Generate a workspace definition JSON from a natural language description.",
    capabilityTags: ["workspace_scaffold"],
    ownerAgentKinds: ["workspace"],
  },
  {
    name: "workspace.create",
    permissionLevel: "confirmed_write",
    writeRiskLevel: "safe",
    summary: "Save a new workspace definition to disk.",
    capabilityTags: ["workspace_create"],
    ownerAgentKinds: ["workspace"],
  },
  {
    name: "workspace.delete",
    permissionLevel: "confirmed_write",
    writeRiskLevel: "risky",
    summary: "Remove a workspace definition from disk.",
    capabilityTags: ["workspace_delete"],
    ownerAgentKinds: ["workspace"],
  },

  // ── Browser ───────────────────────────────────────────────────────────
  {
    name: "browser.navigate",
    permissionLevel: "read",
    summary: "Navigate the browser to a URL and wait for page load.",
    capabilityTags: ["browser_navigate"],
    ownerAgentKinds: ["browser"],
  },
  {
    name: "browser.screenshot",
    permissionLevel: "read",
    summary: "Capture a screenshot of the current page or a specific element.",
    capabilityTags: ["browser_navigate"],
    ownerAgentKinds: ["browser"],
  },
  {
    name: "browser.getContent",
    permissionLevel: "read",
    summary: "Extract text, HTML, or markdown content from the current page.",
    capabilityTags: ["browser_navigate"],
    ownerAgentKinds: ["browser"],
  },
  {
    name: "browser.click",
    permissionLevel: "confirmed_write",
    writeRiskLevel: "risky",
    summary: "Click an element on the page after visible confirmed-write approval.",
    capabilityTags: ["browser_interact"],
    ownerAgentKinds: ["browser"],
  },
  {
    name: "browser.type",
    permissionLevel: "confirmed_write",
    writeRiskLevel: "risky",
    summary: "Type text into an input field after visible confirmed-write approval.",
    capabilityTags: ["browser_interact"],
    ownerAgentKinds: ["browser"],
  },
  {
    name: "browser.evaluate",
    permissionLevel: "confirmed_write",
    writeRiskLevel: "dangerous",
    summary: "Execute JavaScript in the page context after visible confirmed-write approval.",
    capabilityTags: ["browser_interact"],
    ownerAgentKinds: ["browser"],
  },
  {
    name: "browser.runTest",
    permissionLevel: "confirmed_write",
    writeRiskLevel: "risky",
    summary: "Run a Playwright test script after visible confirmed-write approval and return pass/fail results.",
    capabilityTags: ["browser_test"],
    ownerAgentKinds: ["browser"],
  },
  {
    name: "browser.extractLinks",
    permissionLevel: "read",
    summary: "Extract all hyperlinks from the current page with href and text.",
    capabilityTags: ["browser_navigate"],
    ownerAgentKinds: ["browser"],
  },
  {
    name: "browser.upload",
    permissionLevel: "confirmed_write",
    writeRiskLevel: "risky",
    summary: "Upload local file(s) to a file input element on the page. Disabled until browser approvals are implemented.",
    capabilityTags: ["browser_interact"],
    ownerAgentKinds: ["browser"],
  },
  {
    name: "browser.followCandidateLinks",
    permissionLevel: "read",
    summary: "Follow candidate links extracted from the current page and collect content excerpts.",
    capabilityTags: ["browser_navigate"],
    ownerAgentKinds: ["browser"],
  },

  // ── Vision ────────────────────────────────────────────────────────────
  {
    name: "vision.analyze",
    permissionLevel: "read",
    summary: "Analyze an image and answer questions about its visual content.",
    capabilityTags: ["image_analyze"],
    ownerAgentKinds: ["vision"],
  },
  {
    name: "vision.describe",
    permissionLevel: "read",
    summary: "Generate a textual description of an image's visual content.",
    capabilityTags: ["image_describe"],
    ownerAgentKinds: ["vision"],
  },
  {
    name: "vision.extractText",
    permissionLevel: "read",
    summary: "Extract visible text from an image using OCR.",
    capabilityTags: ["image_ocr"],
    ownerAgentKinds: ["vision"],
  },
];
