#!/usr/bin/env python
"""Create a weakly labeled Javis screenshot YOLO dataset using the current detector."""

from __future__ import annotations

import argparse
import json
import random
import shutil
from pathlib import Path
from typing import Any

from PIL import Image
from ultralytics import YOLO


CLASSES = [
    "Button",
    "Text",
    "Image",
    "Icon",
    "Input",
    "Link",
    "Checkbox",
    "Toggle",
    "Toolbar",
    "Navigation",
    "Modal",
    "Tab",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", default="artifacts/local-vision/yolo26n-ui.onnx")
    parser.add_argument("--output", default="artifacts/local-vision/datasets/javis-bootstrap-yolo")
    parser.add_argument("--roots", default="artifacts,docs/qa", help="Comma-separated roots containing PNG screenshots.")
    parser.add_argument("--max-images", type=int, default=120)
    parser.add_argument("--conf", type=float, default=0.01)
    parser.add_argument("--val-ratio", type=float, default=0.1)
    parser.add_argument("--seed", type=int, default=20260609)
    parser.add_argument("--clean", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    output_dir = Path(args.output)
    if args.clean and output_dir.exists():
        shutil.rmtree(output_dir)
    ensure_yolo_dirs(output_dir)

    screenshots = collect_screenshots(args.roots, args.max_images)
    model = YOLO(args.model, task="detect")
    rng = random.Random(args.seed)

    report: dict[str, Any] = {
        "source": "Javis screenshot bootstrap",
        "model": args.model,
        "output": str(output_dir),
        "screenshotsSeen": len(screenshots),
        "imagesWritten": 0,
        "labelsWritten": 0,
        "boxesWritten": 0,
        "skipped": {},
        "classCounts": {name: 0 for name in CLASSES},
        "note": "Weak labels generated by the current detector; not human gold annotations.",
    }

    for index, source in enumerate(screenshots):
        try:
            image = Image.open(source).convert("RGB")
        except Exception:  # noqa: BLE001
            bump(report, "image_open_failed")
            continue
        result = model.predict(source=str(source), imgsz=640, conf=args.conf, verbose=False)[0]
        lines = []
        for box in result.boxes:
            class_id = int(box.cls.item())
            if class_id < 0 or class_id >= len(CLASSES):
                bump(report, "unknown_class")
                continue
            x_center, y_center, width, height = [float(value) for value in box.xywhn[0].tolist()]
            if width <= 0 or height <= 0:
                bump(report, "invalid_box")
                continue
            lines.append(f"{class_id} {x_center:.6f} {y_center:.6f} {width:.6f} {height:.6f}")
            report["classCounts"][CLASSES[class_id]] += 1

        if not lines:
            bump(report, "zero_detections")
            continue

        subset = "val" if rng.random() < args.val_ratio else "train"
        stem = f"javis_bootstrap_{index:06d}"
        image.save(output_dir / "images" / subset / f"{stem}.png")
        (output_dir / "labels" / subset / f"{stem}.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")
        report["imagesWritten"] += 1
        report["labelsWritten"] += 1
        report["boxesWritten"] += len(lines)

    write_data_yaml(output_dir)
    (output_dir / "conversion-report.json").write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(json.dumps(report, indent=2))


def collect_screenshots(roots_arg: str, max_images: int) -> list[Path]:
    roots = [Path(root.strip()) for root in roots_arg.split(",") if root.strip()]
    screenshots: list[Path] = []
    for root in roots:
        if root.is_file() and root.suffix.lower() == ".png":
            screenshots.append(root)
        elif root.exists():
            screenshots.extend(path for path in root.rglob("*.png") if path.is_file())
    screenshots = sorted(set(screenshots), key=lambda path: (str(path.parent), path.name))
    return screenshots[:max_images]


def ensure_yolo_dirs(output_dir: Path) -> None:
    for subset in ("train", "val"):
        (output_dir / "images" / subset).mkdir(parents=True, exist_ok=True)
        (output_dir / "labels" / subset).mkdir(parents=True, exist_ok=True)


def write_data_yaml(output_dir: Path) -> None:
    names = "\n".join(f"  {index}: {name}" for index, name in enumerate(CLASSES))
    yaml = (
        f"path: {output_dir.resolve().as_posix()}\n"
        "train: images/train\n"
        "val: images/val\n"
        "names:\n"
        f"{names}\n"
    )
    (output_dir / "data.yaml").write_text(yaml, encoding="utf-8")


def bump(report: dict[str, Any], key: str) -> None:
    skipped = report.setdefault("skipped", {})
    skipped[key] = skipped.get(key, 0) + 1


if __name__ == "__main__":
    main()
